<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7 Introduction to Sample Size Determination | Topics in Statistical Consulting</title>
  <meta name="description" content="7 Introduction to Sample Size Determination | Topics in Statistical Consulting" />
  <meta name="generator" content="bookdown 0.31 and GitBook 2.6.7" />

  <meta property="og:title" content="7 Introduction to Sample Size Determination | Topics in Statistical Consulting" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7 Introduction to Sample Size Determination | Topics in Statistical Consulting" />
  
  
  



<meta name="date" content="2023-03-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introduction-to-questionnaire-design.html"/>
<link rel="next" href="general-guidelines.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<!-- Latex macros for html output

A few very common things you should use:

- $\bm{}$: Bold math.  Use bold for everything except scalars.
- $\tx{}$: Text within math.  Use for abbreviating words, e.g., $A_{\tx{miss}}$.
- $\xx, \YY$: Default macro convention for bold letters (small and capital case).
- $\aal, \TTh$: Default macro convention for bold symbols (first two letters of symbol name, i.e., $\bm{\alpha}$ and $\bm{\Theta}$).
- common stats symbols e.g., $\var$, $\cov$, $\iid$, $\N, defined below.
-->
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
      TeX: {
	  Macros: {
	      bm: ["\\boldsymbol{#1}",1], <!--bold math-->
	      tx: ["\\textrm{#1}",1], <!--text within math-->
	      rv: ["#2_{#1},\\ldots,#2_{#3}",3,"1"], <!--random variable \rv{X}{n}: X_1, ..., X_n-->
	      iid: ["\\overset{\\;\\tx{iid}\\;}{\\sim}"], <!--iid follows-->
	      ind: ["\\overset{\\:\\tx{ind}\\:}{\\sim}"], <!--ind follows-->
	      var: ["\\operatorname{var}"], <!--variance-->
	      cov: ["\\operatorname{cov}"], <!--coveraince-->
	      cor: ["\\operatorname{cor}"], <!--correlation-->
	      std: ["\\operatorname{se}"], <!--standard error-->
	      diag: ["\\operatorname{diag}"], <!--diagonal matrix-->
	      logit: ["\\operatorname{logit}"], <!--logit function-->
	      N: ["\\mathcal{N}"], <!--normal distribution-->
	      unif: ["\\operatorname{Unif}"], <!--Uniform distribution-->
	      ud: ["\\mathop{}\\!\\mathrm{d}"], <!--d in tegeral-->
	      der: ["\\frac{\\ud^{#1}}{\\ud{#2}^{#1}}", 2, ""], <!--\der{x}{f} d/dx f--> 
	      del: ["\\frac{\\partial^{#1}}{\\partial{#2}^{#1}}", 2, ""], <!--\del{x}{f} d/dx f-->
	      fder: ["\\frac{\\ud^{#1}#3}{\\ud{#2}^{#1}}", 3, ""], <!--\fder{x}{f} df/dx -->
	      fdel: ["\\frac{\\partial^{#1}#3}{\\partial{#2}^{#1}}", 3, ""], <!--\fdel{x}{f} df/dx -->
	      hess: ["\\frac{\\partial^2}{\\partial{#1}\\partial{#1}'}", 1], <!--\hess{x} d/dxdx -->
	      fhess: ["\\frac{\\partial^2#2}{\\partial{#1}\\partial{#1}'}", 2], <!--\fhess{x}{f} df/dxdx -->
              kbt: ["k_{\\tx{B}}T"],
	      IH: ["{\\mathfrak P}"], <!--p curl-->
	      eps: ["\\varepsilon"], <!--epsilon-->
	      paug: ["p_{\\tx{A}}"], <!--p_A-->
	      Ka: ["{\\mathcal K}"], <!--K curl-->
	      Ua: ["{\\mathcal U}"], <!--U curl-->
	      Ha: ["{\\mathcal H}"], <!--H curl-->
	      curr: ["{\\tx{curr}}"], <!--curr-->
	      prop: ["{\\tx{prop}}"], <!--prop-->
	      obs: ["{\\tx{obs}}"], <!--obs-->
	      bz: ["{\\bm{0}}"], <!--boldface 0-->
	      mm: ["{\\bm{m}}"], <!--boldface m-->
	      ww: ["{\\bm{w}}"], <!--boldface w-->
	      vv: ["{\\bm{v}}"], <!--boldface v-->
	      xx: ["{\\bm{x}}"], <!--boldface x-->
	      yy: ["{\\bm{y}}"], <!--boldface y-->
	      zz: ["{\\bm{z}}"], <!--boldface z-->
	      UU: ["{\\bm{U}}"], <!--boldface U-->
	      II: ["{\\bm{I}}"], <!--boldface I-->
	      HH: ["{\\bm{H}}"], <!--boldface H-->
	      XX: ["{\\bm{X}}"], <!--boldface X-->
	      YY: ["{\\bm{Y}}"], <!--boldface Y-->
	      ZZ: ["{\\bm{Z}}"], <!--boldface Z-->
	      aal: ["{\\bm{\\alpha}}"], <!--boldface alpha-->
	      bbe: ["{\\bm{\\beta}}"], <!--boldface beta-->
	      gga: ["{\\bm{\\gamma}}"], <!--boldface gamma-->
	      eet: ["{\\bm{\\eta}}"], <!--boldface eta-->
	      lla: ["{\\bm{\\lambda}}"], <!--boldface lambda-->
	      mmu: ["{\\bm{\\mu}}"], <!--boldface mu-->
	      pph: ["{\\bm{\\phi}}"], <!--boldface phi-->
	      pps: ["{\\bm{\\psi}}"], <!--boldface psi-->
	      rrh: ["{\\bm{\\rho}}"], <!--boldface rho-->
	      ssi: ["{\\bm{\\sigma}}"], <!--boldface sigma-->
	      tta: ["{\\bm{\\tau}}"], <!--boldface tau-->
	      tth: ["{\\bm{\\theta}}"], <!--boldface theta-->
	      eeps: ["{\\bm{\\varepsilon}}"], <!--boldface varepsilon-->
	      GGa: ["{\\bm{\\Gamma}}"], <!--boldface Gamma-->
	      SSi: ["{\\bm{\\Sigma}}"], <!--boldface Sigma-->
	      TTh: ["{\\bm{\\Theta}}"], <!--boldface Theta-->
	      cU: ["\\bm{\\mathcal{U}}"], <!--boldface U curl-->
	      rx: ["{\\tx{x}}"], <!--text x-->
	      ry: ["{\\tx{y}}"], <!--text y-->
	      rz: ["{\\tx{z}}"], <!--text z-->
	      rvx: ["{\\mathbf{x}}"], <!--boldface text x-->
	      rvz: ["{\\mathbf{z}}"], <!--boldface text z-->
	      rvc: ["{\\mathbf{c}}"], <!--boldface text c-->
	      rvzl: ["{\\mathbf{z}^{\\tx{l}}}"], <!--bold face z^l-->
	      rvzg: ["{\\mathbf{z}^{\\tx{g}}}"], <!--bold face z^g-->
	      rvt: ["{\\mathbf{t}}"], <!--boldface t-->
	      Q: ["{\\mathcal{Q}}"], <!--Q curl-->
	      O: ["{\\mathcal{O}}"], <!--O curl-->
	      U: ["{\\mathcal{U}}"], <!--U curl-->
	      R: ["{\\mathbb{R}}"], <!--real set-->
	      kl: ["{\\operatorname{KL}}"], <!--KL-->
	      sfT: ["{\\mathsf{T}}"], <!--sf T-->
	      sfk: ["{\\mathsf{k}}"], <!--sf k-->
	      sfa: ["{\\mathsf{a}}"], <!--sf a-->
	      sfh: ["{\\mathsf{h}}"], <!--sf h-->
  	      sfkl: ["{\\mathsf{k}^{\\tx{l}}}"], <!--sf k^l-->
	      sfal: ["{\\mathsf{a}^{\\tx{l}}}"], <!--sf a^l-->
	      sfhl: ["{\\mathsf{h}^{\\tx{l}}}"], <!--sf h^l-->
  	      sfkg: ["{\\mathsf{k}^{\\tx{g}}}"], <!--sf k^g-->
	      sfag: ["{\\mathsf{a}^{\\tx{g}}}"], <!--sf a^g-->
	      sfhg: ["{\\mathsf{h}^{\\tx{g}}}"], <!--sf h^g-->
	      sft: ["{\\mathsf{t}}"], <!--sf t-->
	      sfr: ["{\\mathsf{r}}"], <!--sf r-->
	      argmin: ["\\operatorname{arg\\,min}"], <!--argmin-->
	      argmax: ["\\operatorname{arg\\,max}"], <!--argmax-->
	      E: ["{\\mathbb{E}}"], <!--expectation-->
	      L: ["{\\mathcal{L}}"], <!--curl L likelihood-->
	      ellap: ["\\ell_{\\tx{Lap}}"] <!--curl l_Lap-->
	  }
      }
  });
</script>



<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://uwaterloo.ca/statistical-consulting-and-collaborative-research-unit/" target="blank">Statistical Consulting and Collaborative Research Unit</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#authors"><i class="fa fa-check"></i>Authors</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#editors"><i class="fa fa-check"></i>Editors</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> R and RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#basic-r"><i class="fa fa-check"></i><b>1.2</b> Basic R</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#rintro-calculate"><i class="fa fa-check"></i><b>1.2.1</b> Calculating with R</a></li>
<li class="chapter" data-level="1.2.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#variables"><i class="fa fa-check"></i><b>1.2.2</b> Variables</a></li>
<li class="chapter" data-level="1.2.3" data-path="introduction-to-r.html"><a href="introduction-to-r.html#vectors"><i class="fa fa-check"></i><b>1.2.3</b> Vectors</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-r.html"><a href="introduction-to-r.html#basic-data-analysis-workflow"><i class="fa fa-check"></i><b>1.3</b> Basic Data Analysis Workflow</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#reading-data-into-r"><i class="fa fa-check"></i><b>1.3.1</b> Reading Data into R</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#descriptive-statistics"><i class="fa fa-check"></i><b>1.3.2</b> Descriptive Statistics</a></li>
<li class="chapter" data-level="1.3.3" data-path="introduction-to-r.html"><a href="introduction-to-r.html#data-visualization"><i class="fa fa-check"></i><b>1.3.3</b> Data Visualization</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-r.html"><a href="introduction-to-r.html#some-coding-tips"><i class="fa fa-check"></i><b>1.4</b> Some Coding Tips</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#source-editor"><i class="fa fa-check"></i><b>1.4.1</b> Source Editor</a></li>
<li class="chapter" data-level="1.4.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#commenting"><i class="fa fa-check"></i><b>1.4.2</b> Commenting</a></li>
<li class="chapter" data-level="1.4.3" data-path="introduction-to-r.html"><a href="introduction-to-r.html#saving-the-environment"><i class="fa fa-check"></i><b>1.4.3</b> Saving the Environment</a></li>
<li class="chapter" data-level="1.4.4" data-path="introduction-to-r.html"><a href="introduction-to-r.html#installing-and-loading-libraries"><i class="fa fa-check"></i><b>1.4.4</b> Installing and Loading Libraries</a></li>
<li class="chapter" data-level="1.4.5" data-path="introduction-to-r.html"><a href="introduction-to-r.html#good-coding-practices"><i class="fa fa-check"></i><b>1.4.5</b> Good Coding Practices</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="introduction-to-r.html"><a href="introduction-to-r.html#getting-help"><i class="fa fa-check"></i><b>1.5</b> Getting Help</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#r-documentation"><i class="fa fa-check"></i><b>1.5.1</b> R Documentation</a></li>
<li class="chapter" data-level="1.5.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#online-resources"><i class="fa fa-check"></i><b>1.5.2</b> Online Resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction-to-ggplot2.html"><a href="introduction-to-ggplot2.html"><i class="fa fa-check"></i><b>2</b> Introduction to ggplot2</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introduction-to-ggplot2.html"><a href="introduction-to-ggplot2.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="introduction-to-ggplot2.html"><a href="introduction-to-ggplot2.html#example-data-set"><i class="fa fa-check"></i><b>2.1.1</b> Example Data Set</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="introduction-to-ggplot2.html"><a href="introduction-to-ggplot2.html#data"><i class="fa fa-check"></i><b>2.2</b> Data</a></li>
<li class="chapter" data-level="2.3" data-path="introduction-to-ggplot2.html"><a href="introduction-to-ggplot2.html#aesthetics"><i class="fa fa-check"></i><b>2.3</b> Aesthetics</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="introduction-to-ggplot2.html"><a href="introduction-to-ggplot2.html#the-colour-component"><i class="fa fa-check"></i><b>2.3.1</b> The Colour Component</a></li>
<li class="chapter" data-level="2.3.2" data-path="introduction-to-ggplot2.html"><a href="introduction-to-ggplot2.html#the-size-component"><i class="fa fa-check"></i><b>2.3.2</b> The Size Component</a></li>
<li class="chapter" data-level="2.3.3" data-path="introduction-to-ggplot2.html"><a href="introduction-to-ggplot2.html#the-shape-component"><i class="fa fa-check"></i><b>2.3.3</b> The Shape Component</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="introduction-to-ggplot2.html"><a href="introduction-to-ggplot2.html#geometrics"><i class="fa fa-check"></i><b>2.4</b> Geometrics</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="introduction-to-ggplot2.html"><a href="introduction-to-ggplot2.html#line-graphs"><i class="fa fa-check"></i><b>2.4.1</b> Line Graphs</a></li>
<li class="chapter" data-level="2.4.2" data-path="introduction-to-ggplot2.html"><a href="introduction-to-ggplot2.html#bar-plots"><i class="fa fa-check"></i><b>2.4.2</b> Bar Plots</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="introduction-to-ggplot2.html"><a href="introduction-to-ggplot2.html#others"><i class="fa fa-check"></i><b>2.5</b> Others</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="introduction-to-ggplot2.html"><a href="introduction-to-ggplot2.html#axes-labels"><i class="fa fa-check"></i><b>2.5.1</b> Axes Labels</a></li>
<li class="chapter" data-level="2.5.2" data-path="introduction-to-ggplot2.html"><a href="introduction-to-ggplot2.html#title-of-the-graph"><i class="fa fa-check"></i><b>2.5.2</b> Title of the Graph</a></li>
<li class="chapter" data-level="2.5.3" data-path="introduction-to-ggplot2.html"><a href="introduction-to-ggplot2.html#legends"><i class="fa fa-check"></i><b>2.5.3</b> Legends</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html"><i class="fa fa-check"></i><b>3</b> Introduction to Linear Regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#introduction-1"><i class="fa fa-check"></i><b>3.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#list-of-r-packages-used"><i class="fa fa-check"></i><b>3.1.1</b> List of R packages Used</a></li>
<li class="chapter" data-level="3.1.2" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#motivating-example"><i class="fa fa-check"></i><b>3.1.2</b> Motivating Example</a></li>
<li class="chapter" data-level="3.1.3" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#variables-1"><i class="fa fa-check"></i><b>3.1.3</b> Variables</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#linreg-slm"><i class="fa fa-check"></i><b>3.2</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#linreg-slm-assumption"><i class="fa fa-check"></i><b>3.2.1</b> Assumptions</a></li>
<li class="chapter" data-level="3.2.2" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#linreg-slm-est"><i class="fa fa-check"></i><b>3.2.2</b> Estimation</a></li>
<li class="chapter" data-level="3.2.3" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#inference"><i class="fa fa-check"></i><b>3.2.3</b> Inference</a></li>
<li class="chapter" data-level="3.2.4" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#linreg-slm-modelcheck"><i class="fa fa-check"></i><b>3.2.4</b> Model Checking</a></li>
<li class="chapter" data-level="3.2.5" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#simple-linear-regression-on-a-binary-covariate"><i class="fa fa-check"></i><b>3.2.5</b> Simple Linear Regression on a Binary Covariate</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#linreg-mlm"><i class="fa fa-check"></i><b>3.3</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#linreg-mlm-est"><i class="fa fa-check"></i><b>3.3.1</b> Estimation</a></li>
<li class="chapter" data-level="3.3.2" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#interaction-effects"><i class="fa fa-check"></i><b>3.3.2</b> Interaction Effects</a></li>
<li class="chapter" data-level="3.3.3" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#model-selection"><i class="fa fa-check"></i><b>3.3.3</b> Model Selection</a></li>
<li class="chapter" data-level="3.3.4" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#model-diagnostics"><i class="fa fa-check"></i><b>3.3.4</b> Model Diagnostics</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#further-extensions"><i class="fa fa-check"></i><b>3.4</b> Further Extensions</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#recommendations"><i class="fa fa-check"></i><b>3.4.1</b> Recommendations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html"><i class="fa fa-check"></i><b>4</b> Introduction to Nonparametric Statistics</a>
<ul>
<li class="chapter" data-level="4.1" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#introduction-2"><i class="fa fa-check"></i><b>4.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#r-packages-and-data"><i class="fa fa-check"></i><b>4.1.1</b> R Packages and Data</a></li>
<li class="chapter" data-level="4.1.2" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#nonpram-rank"><i class="fa fa-check"></i><b>4.1.2</b> Sample Ranks</a></li>
<li class="chapter" data-level="4.1.3" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#nonpram-sd"><i class="fa fa-check"></i><b>4.1.3</b> Sampling Distribution</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#two-sample-hypothesis-testing"><i class="fa fa-check"></i><b>4.2</b> Two-sample Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#quick-reference-table"><i class="fa fa-check"></i><b>4.2.1</b> Quick Reference Table</a></li>
<li class="chapter" data-level="4.2.2" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#nonpram-mwu"><i class="fa fa-check"></i><b>4.2.2</b> Wilcoxon Rank-Sum Test</a></li>
<li class="chapter" data-level="4.2.3" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#other-softwares"><i class="fa fa-check"></i><b>4.2.3</b> Other Softwares</a></li>
<li class="chapter" data-level="4.2.4" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#nonpram-wst"><i class="fa fa-check"></i><b>4.2.4</b> Wilcoxon Signed Rank Test</a></li>
<li class="chapter" data-level="4.2.5" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#nonpram-tst"><i class="fa fa-check"></i><b>4.2.5</b> Siegel-Tukey Test</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#nonpram-anova"><i class="fa fa-check"></i><b>4.3</b> ANOVA-type Methods</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#one-way-anova"><i class="fa fa-check"></i><b>4.3.1</b> One-way ANOVA</a></li>
<li class="chapter" data-level="4.3.2" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#post-hoc-comparisons-for-kw-anova"><i class="fa fa-check"></i><b>4.3.2</b> Post Hoc Comparisons for KW ANOVA</a></li>
<li class="chapter" data-level="4.3.3" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#repeated-measures-anova-friedman-test"><i class="fa fa-check"></i><b>4.3.3</b> Repeated Measures ANOVA (Friedman Test)</a></li>
<li class="chapter" data-level="4.3.4" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#post-hoc-tests"><i class="fa fa-check"></i><b>4.3.4</b> Post Hoc tests</a></li>
<li class="chapter" data-level="4.3.5" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#an-example-using-r-6"><i class="fa fa-check"></i><b>4.3.5</b> An example using R</a></li>
<li class="chapter" data-level="4.3.6" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#additional-resources-for-nonparametric-anova-procedures"><i class="fa fa-check"></i><b>4.3.6</b> Additional Resources for Nonparametric ANOVA Procedures</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#boostrap-methods"><i class="fa fa-check"></i><b>4.4</b> Boostrap Methods</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#bootstrap-confidence-intervals"><i class="fa fa-check"></i><b>4.4.1</b> Bootstrap Confidence Intervals</a></li>
<li class="chapter" data-level="4.4.2" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#assumptions"><i class="fa fa-check"></i><b>4.4.2</b> Assumptions</a></li>
<li class="chapter" data-level="4.4.3" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#examples-using-r"><i class="fa fa-check"></i><b>4.4.3</b> Examples using R</a></li>
<li class="chapter" data-level="4.4.4" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#additional-resources"><i class="fa fa-check"></i><b>4.4.4</b> Additional Resources</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#random-forests"><i class="fa fa-check"></i><b>4.5</b> Random Forests</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#examples-using-r-1"><i class="fa fa-check"></i><b>4.5.1</b> Examples Using R</a></li>
<li class="chapter" data-level="4.5.2" data-path="introduction-to-nonparametric-statistics.html"><a href="introduction-to-nonparametric-statistics.html#nonpram-arrf"><i class="fa fa-check"></i><b>4.5.2</b> Additional Resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html"><i class="fa fa-check"></i><b>5</b> Introduction to Longitudinal Data</a>
<ul>
<li class="chapter" data-level="5.1" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#introduction-3"><i class="fa fa-check"></i><b>5.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-rpackages"><i class="fa fa-check"></i><b>5.1.1</b> List of R packages Used</a></li>
<li class="chapter" data-level="5.1.2" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-motivating"><i class="fa fa-check"></i><b>5.1.2</b> Motivating Example</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-datastruc"><i class="fa fa-check"></i><b>5.2</b> Data Structure for Longitudinal Responses</a></li>
<li class="chapter" data-level="5.3" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linear"><i class="fa fa-check"></i><b>5.3</b> Linear Models for Continuous Outcome</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linear-assumptions"><i class="fa fa-check"></i><b>5.3.1</b> Assumptions</a></li>
<li class="chapter" data-level="5.3.2" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linear-modelspec"><i class="fa fa-check"></i><b>5.3.2</b> Notation and Model Specification</a></li>
<li class="chapter" data-level="5.3.3" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linear-corr"><i class="fa fa-check"></i><b>5.3.3</b> Correlation Structures</a></li>
<li class="chapter" data-level="5.3.4" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linear-estimation"><i class="fa fa-check"></i><b>5.3.4</b> Estimation</a></li>
<li class="chapter" data-level="5.3.5" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linear-R"><i class="fa fa-check"></i><b>5.3.5</b> Modelling in R</a></li>
<li class="chapter" data-level="5.3.6" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linear-HT"><i class="fa fa-check"></i><b>5.3.6</b> Hypothesis Testing</a></li>
<li class="chapter" data-level="5.3.7" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linear-population"><i class="fa fa-check"></i><b>5.3.7</b> Population Means</a></li>
<li class="chapter" data-level="5.3.8" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linear-cov"><i class="fa fa-check"></i><b>5.3.8</b> Selecting a Correlation Structure</a></li>
<li class="chapter" data-level="5.3.9" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linear-procedure"><i class="fa fa-check"></i><b>5.3.9</b> Model Fitting Procedure</a></li>
<li class="chapter" data-level="5.3.10" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linear-example2"><i class="fa fa-check"></i><b>5.3.10</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linearmixed"><i class="fa fa-check"></i><b>5.4</b> Linear Mixed Effect Models for Longitudinal Data</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linearmixed-notation"><i class="fa fa-check"></i><b>5.4.1</b> Notation and Model Specification</a></li>
<li class="chapter" data-level="5.4.2" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linearmixed-randomintercept"><i class="fa fa-check"></i><b>5.4.2</b> Random Intercept Models</a></li>
<li class="chapter" data-level="5.4.3" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linearmixed-randominterceptslope"><i class="fa fa-check"></i><b>5.4.3</b> Random Intercept and Slope Models</a></li>
<li class="chapter" data-level="5.4.4" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linearmixed-estimation"><i class="fa fa-check"></i><b>5.4.4</b> Estimation</a></li>
<li class="chapter" data-level="5.4.5" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linearmixed-R"><i class="fa fa-check"></i><b>5.4.5</b> Modelling in R</a></li>
<li class="chapter" data-level="5.4.6" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linearmixed-diagnostics"><i class="fa fa-check"></i><b>5.4.6</b> Model Diagnostics for Linear Mixed Effects Models</a></li>
<li class="chapter" data-level="5.4.7" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linearmixed-popmeans"><i class="fa fa-check"></i><b>5.4.7</b> Population Means</a></li>
<li class="chapter" data-level="5.4.8" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-linearmixed-ht"><i class="fa fa-check"></i><b>5.4.8</b> Hypothesis Testing for Fixed Effects</a></li>
<li class="chapter" data-level="5.4.9" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-lme-modelfitting"><i class="fa fa-check"></i><b>5.4.9</b> Model Fitting Procedure</a></li>
<li class="chapter" data-level="5.4.10" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#long-lme-ex2"><i class="fa fa-check"></i><b>5.4.10</b> Example - Milk Protein and Diet</a></li>
<li class="chapter" data-level="5.4.11" data-path="introduction-to-longitudinal-data.html"><a href="introduction-to-longitudinal-data.html#example---aids-clinical-trial-group"><i class="fa fa-check"></i><b>5.4.11</b> Example - AIDS Clinical Trial Group</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="introduction-to-questionnaire-design.html"><a href="introduction-to-questionnaire-design.html"><i class="fa fa-check"></i><b>6</b> Introduction to Questionnaire Design</a>
<ul>
<li class="chapter" data-level="6.1" data-path="introduction-to-questionnaire-design.html"><a href="introduction-to-questionnaire-design.html#questdes-plan"><i class="fa fa-check"></i><b>6.1</b> Plan the Study</a></li>
<li class="chapter" data-level="6.2" data-path="introduction-to-questionnaire-design.html"><a href="introduction-to-questionnaire-design.html#questdes-prepare"><i class="fa fa-check"></i><b>6.2</b> Prepare the Questions</a></li>
<li class="chapter" data-level="6.3" data-path="introduction-to-questionnaire-design.html"><a href="introduction-to-questionnaire-design.html#questdes-put"><i class="fa fa-check"></i><b>6.3</b> Put Together the Questionnaire</a></li>
<li class="chapter" data-level="6.4" data-path="introduction-to-questionnaire-design.html"><a href="introduction-to-questionnaire-design.html#questdes-pretest"><i class="fa fa-check"></i><b>6.4</b> Pretest the Questionnaire</a></li>
<li class="chapter" data-level="6.5" data-path="introduction-to-questionnaire-design.html"><a href="introduction-to-questionnaire-design.html#a-checklist-for-questionnaire-designs"><i class="fa fa-check"></i><b>6.5</b> A Checklist for Questionnaire Designs</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="introduction-to-sample-size-determination.html"><a href="introduction-to-sample-size-determination.html"><i class="fa fa-check"></i><b>7</b> Introduction to Sample Size Determination</a>
<ul>
<li class="chapter" data-level="7.1" data-path="introduction-to-sample-size-determination.html"><a href="introduction-to-sample-size-determination.html#introduction-4"><i class="fa fa-check"></i><b>7.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="introduction-to-sample-size-determination.html"><a href="introduction-to-sample-size-determination.html#samp-rpackages"><i class="fa fa-check"></i><b>7.1.1</b> List of R Packages Used</a></li>
<li class="chapter" data-level="7.1.2" data-path="introduction-to-sample-size-determination.html"><a href="introduction-to-sample-size-determination.html#samp-errors"><i class="fa fa-check"></i><b>7.1.2</b> Type I and Type II Errors</a></li>
<li class="chapter" data-level="7.1.3" data-path="introduction-to-sample-size-determination.html"><a href="introduction-to-sample-size-determination.html#samp-effect-size"><i class="fa fa-check"></i><b>7.1.3</b> Effect Size</a></li>
<li class="chapter" data-level="7.1.4" data-path="introduction-to-sample-size-determination.html"><a href="introduction-to-sample-size-determination.html#samp-equivalence"><i class="fa fa-check"></i><b>7.1.4</b> Equivalence Testing</a></li>
<li class="chapter" data-level="7.1.5" data-path="introduction-to-sample-size-determination.html"><a href="introduction-to-sample-size-determination.html#samp-precision"><i class="fa fa-check"></i><b>7.1.5</b> Precision-Based Sample Size Determination</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="introduction-to-sample-size-determination.html"><a href="introduction-to-sample-size-determination.html#samp-common-models"><i class="fa fa-check"></i><b>7.2</b> Sample Size Determination for Common Models</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="introduction-to-sample-size-determination.html"><a href="introduction-to-sample-size-determination.html#pwr-pckg"><i class="fa fa-check"></i><b>7.2.1</b> The pwr Package</a></li>
<li class="chapter" data-level="7.2.2" data-path="introduction-to-sample-size-determination.html"><a href="introduction-to-sample-size-determination.html#gpower-software"><i class="fa fa-check"></i><b>7.2.2</b> G*Power Software</a></li>
<li class="chapter" data-level="7.2.3" data-path="introduction-to-sample-size-determination.html"><a href="introduction-to-sample-size-determination.html#samp-ex-ANOVA"><i class="fa fa-check"></i><b>7.2.3</b> Sample Size Determination for Balanced One-Way ANOVA</a></li>
<li class="chapter" data-level="7.2.4" data-path="introduction-to-sample-size-determination.html"><a href="introduction-to-sample-size-determination.html#samp-ex-mlr"><i class="fa fa-check"></i><b>7.2.4</b> Sample Size Determination for Multiple Regression Model</a></li>
<li class="chapter" data-level="7.2.5" data-path="introduction-to-sample-size-determination.html"><a href="introduction-to-sample-size-determination.html#samp-ex-t"><i class="fa fa-check"></i><b>7.2.5</b> Sample Size Determination to Compare Two Means (Unknown, Common Variance)</a></li>
<li class="chapter" data-level="7.2.6" data-path="introduction-to-sample-size-determination.html"><a href="introduction-to-sample-size-determination.html#samp-TOSTER"><i class="fa fa-check"></i><b>7.2.6</b> The TOSTER Package</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="introduction-to-sample-size-determination.html"><a href="introduction-to-sample-size-determination.html#samp-sec-sim"><i class="fa fa-check"></i><b>7.3</b> Simulation-Based Sample Size Determination</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="introduction-to-sample-size-determination.html"><a href="introduction-to-sample-size-determination.html#samp-sim-sing"><i class="fa fa-check"></i><b>7.3.1</b> Computing a Single Power Estimation via Simulation</a></li>
<li class="chapter" data-level="7.3.2" data-path="introduction-to-sample-size-determination.html"><a href="introduction-to-sample-size-determination.html#samp-est-curve"><i class="fa fa-check"></i><b>7.3.2</b> Estimating a Power Curve via Simulation</a></li>
<li class="chapter" data-level="7.3.3" data-path="introduction-to-sample-size-determination.html"><a href="introduction-to-sample-size-determination.html#samp-parallel"><i class="fa fa-check"></i><b>7.3.3</b> Parallelization for Simulation-Based Sample Size Determination</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="introduction-to-sample-size-determination.html"><a href="introduction-to-sample-size-determination.html#samp-beyond"><i class="fa fa-check"></i><b>7.4</b> Beyond Sample Size Determination</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="general-guidelines.html"><a href="general-guidelines.html"><i class="fa fa-check"></i><b>A</b> General Guidelines</a>
<ul>
<li class="chapter" data-level="A.1" data-path="general-guidelines.html"><a href="general-guidelines.html#resources"><i class="fa fa-check"></i><b>A.1</b> Resources</a></li>
<li class="chapter" data-level="A.2" data-path="general-guidelines.html"><a href="general-guidelines.html#format"><i class="fa fa-check"></i><b>A.2</b> Format</a>
<ul>
<li class="chapter" data-level="A.2.1" data-path="general-guidelines.html"><a href="general-guidelines.html#typesetting-math"><i class="fa fa-check"></i><b>A.2.1</b> Typesetting Math</a></li>
<li class="chapter" data-level="A.2.2" data-path="general-guidelines.html"><a href="general-guidelines.html#genguide-citations"><i class="fa fa-check"></i><b>A.2.2</b> Citations</a></li>
</ul></li>
<li class="chapter" data-level="A.3" data-path="general-guidelines.html"><a href="general-guidelines.html#rendering-the-book"><i class="fa fa-check"></i><b>A.3</b> Rendering the Book</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="formatting-guidelines.html"><a href="formatting-guidelines.html"><i class="fa fa-check"></i><b>B</b> Formatting Guidelines</a>
<ul>
<li class="chapter" data-level="B.1" data-path="formatting-guidelines.html"><a href="formatting-guidelines.html#formatguide-general"><i class="fa fa-check"></i><b>B.1</b> General</a></li>
<li class="chapter" data-level="B.2" data-path="formatting-guidelines.html"><a href="formatting-guidelines.html#embedding-files"><i class="fa fa-check"></i><b>B.2</b> Embedding Files</a></li>
<li class="chapter" data-level="B.3" data-path="formatting-guidelines.html"><a href="formatting-guidelines.html#math"><i class="fa fa-check"></i><b>B.3</b> Math</a>
<ul>
<li class="chapter" data-level="B.3.1" data-path="formatting-guidelines.html"><a href="formatting-guidelines.html#commonly-used-math-and-stats-expressions"><i class="fa fa-check"></i><b>B.3.1</b> Commonly-Used Math and Stats Expressions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="C" data-path="git-and-github-a-quick-tutorial.html"><a href="git-and-github-a-quick-tutorial.html"><i class="fa fa-check"></i><b>C</b> Git and GitHub: A Quick Tutorial</a>
<ul>
<li class="chapter" data-level="C.1" data-path="git-and-github-a-quick-tutorial.html"><a href="git-and-github-a-quick-tutorial.html#setup"><i class="fa fa-check"></i><b>C.1</b> Setup</a></li>
<li class="chapter" data-level="C.2" data-path="git-and-github-a-quick-tutorial.html"><a href="git-and-github-a-quick-tutorial.html#contributing-to-the-project"><i class="fa fa-check"></i><b>C.2</b> Contributing to the Project</a></li>
<li class="chapter" data-level="C.3" data-path="git-and-github-a-quick-tutorial.html"><a href="git-and-github-a-quick-tutorial.html#git-mistakes"><i class="fa fa-check"></i><b>C.3</b> Git Mistakes</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="bookdown-tests.html"><a href="bookdown-tests.html"><i class="fa fa-check"></i><b>D</b> Bookdown Tests</a>
<ul>
<li class="chapter" data-level="D.1" data-path="bookdown-tests.html"><a href="bookdown-tests.html#test-math-macros"><i class="fa fa-check"></i><b>D.1</b> Test Math Macros</a></li>
<li class="chapter" data-level="D.2" data-path="bookdown-tests.html"><a href="bookdown-tests.html#test-figure"><i class="fa fa-check"></i><b>D.2</b> Test Figure</a></li>
<li class="chapter" data-level="D.3" data-path="bookdown-tests.html"><a href="bookdown-tests.html#test-cran-link"><i class="fa fa-check"></i><b>D.3</b> Test CRAN Link</a></li>
<li class="chapter" data-level="D.4" data-path="bookdown-tests.html"><a href="bookdown-tests.html#test-checklist"><i class="fa fa-check"></i><b>D.4</b> Test Checklist</a></li>
<li class="chapter" data-level="D.5" data-path="bookdown-tests.html"><a href="bookdown-tests.html#test-references"><i class="fa fa-check"></i><b>D.5</b> Test References</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Topics in Statistical Consulting</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introduction-to-sample-size-determination" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">7</span> Introduction to Sample Size Determination<a href="introduction-to-sample-size-determination.html#introduction-to-sample-size-determination" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><em>Author: Luke Hagar</em></p>
<p><em>Last Updated: October 17, 2022</em></p>
<div id="introduction-4" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Introduction<a href="introduction-to-sample-size-determination.html#introduction-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Sample size determination involves choosing the number of observations to include in a statistical sample. It is an important component of experimental design. Clients often visit the SSCR for statistical advice after the data collection process is complete. Sometimes, these clients have collected very small samples for their study, which can greatly complicate the analysis. In some cases, we may find major flaws in the study design and recommend that they redo the study. To avoid these situations, it is best to thoroughly consider sample size determination while designing a study. We note that some clients may have very limited funding and not be able to collect large samples, but considering sample size determination beforehand can help (i) set realistic expectations for the study or (ii) support the use of simpler statistical models when analyzing the data.</p>
<p>There are both practical and statistical considerations that inform sample size determination. Practical considerations for sample size determination include the cost of sampling each observation (sometimes called an experimental unit), the time associated with collecting each observation, and the convenience with which observations can be sampled. Statistical considerations include the statistical power (to be discussed) of the designed study and the precision of its relevant estimates. This chapter focuses on the statistical considerations for sample size determination, but it may be useful to also discuss practical considerations for sample size determination with clients.</p>
<div id="samp-rpackages" class="section level3 hasAnchor" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> List of R Packages Used<a href="introduction-to-sample-size-determination.html#samp-rpackages" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this chapter, we will be using the packages <a href="https://cran.r-project.org/web/packages/pwr/"><strong>pwr</strong></a>, <a href="https://cran.r-project.org/web/packages/TOSTER/"><strong>TOSTER</strong></a>, <a href="https://cran.r-project.org/web/packages/foreach/"><strong>foreach</strong></a>, <a href="https://cran.r-project.org/web/packages/doParallel/"><strong>doParallel</strong></a>, and <a href="https://cran.r-project.org/web/packages/doSNOW/"><strong>doSNOW</strong></a>. We will also discuss the free sample size determination software <a href="https://www.psychologie.hhu.de/arbeitsgruppen/allgemeine-psychologie-und-arbeitspsychologie/gpower.html">G<span class="math inline">\(^*\)</span>Power</a>.</p>
<div class="sourceCode" id="cb456"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb456-1"><a href="introduction-to-sample-size-determination.html#cb456-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pwr) <span class="do">## load the required packages</span></span>
<span id="cb456-2"><a href="introduction-to-sample-size-determination.html#cb456-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(TOSTER)</span>
<span id="cb456-3"><a href="introduction-to-sample-size-determination.html#cb456-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(foreach)</span>
<span id="cb456-4"><a href="introduction-to-sample-size-determination.html#cb456-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(doParallel)</span>
<span id="cb456-5"><a href="introduction-to-sample-size-determination.html#cb456-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(doSNOW)</span></code></pre></div>
</div>
<div id="samp-errors" class="section level3 hasAnchor" number="7.1.2">
<h3><span class="header-section-number">7.1.2</span> Type I and Type II Errors<a href="introduction-to-sample-size-determination.html#samp-errors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Most statistical studies involve testing a hypothesis of interest. When testing a hypothesis using statistical hypothesis tests, we can make two types of errors. To introduce these types of errors, we use a standard two-sample hypothesis test where we wish to test a one-sided hypothesis. We let <span class="math inline">\(\mu_1\)</span> be the mean response for the first group and <span class="math inline">\(\mu_2\)</span> be the mean response for the second group. The null and alternative hypotheses for this test are
<span class="math display">\[H_0: \mu_1 \ge \mu_2 ~~~\text{vs.}~~~ H_A: \mu_1 &lt; \mu_2.\]</span></p>
<p>We typically decide whether or not to reject the null hypothesis using <span class="math inline">\(p\)</span>-values. If the <span class="math inline">\(p\)</span>-value is smaller than a predetermined threshold <span class="math inline">\(\alpha\)</span>, then we reject <span class="math inline">\(H_0\)</span>; otherwise, we do not reject the null hypothesis. This type of standard hypothesis test does not allow us to accept the null hypothesis. In the frequentist framework, we consider <span class="math inline">\(\mu_1\)</span> and <span class="math inline">\(\mu_2\)</span> to be fixed, unknown values. Therefore, we do not known whether the statement <span class="math inline">\(\mu_1 \ge \mu_2\)</span> is true or false, but it <em>is</em> either true or false.</p>
<p>A type I error occurs when we incorrectly reject the null hypothesis. For this example, that means that we reject <span class="math inline">\(H_0\)</span> when <span class="math inline">\(\mu_1\)</span> is indeed at least equal to <span class="math inline">\(\mu_2\)</span>. A type II error occurs when we incorrectly do not reject the null hypothesis. For this example, this means that we do not reject <span class="math inline">\(H_0\)</span> when <span class="math inline">\(\mu_1\)</span> is less than <span class="math inline">\(\mu_2\)</span>. Before discussing how to control the probability of making a type I or II error, it may be helpful to explain to the client what the consequences of making type I and II errors mean in the context of their experiment. Let’s imagine that <span class="math inline">\(\mu_1\)</span> and <span class="math inline">\(\mu_2\)</span> represent the mean patient survival time for two types of cancer treatments. Treatment 1 (corresponding to <span class="math inline">\(\mu_1\)</span>) is the standard existing treatment, whereas treatment 2 (corresponding to <span class="math inline">\(\mu_2\)</span>) is a novel treatment. Clinicians might recommend replacing the standard treatment with treatment 2 if we obtain enough evidence to reject the null hypothesis <span class="math inline">\(H_0: \mu_1 \ge \mu_2\)</span>. In this situation, a type I error would result in replacing the existing cancer treatment with an inferior one. A type II error would result in not replacing the existing cancer treatment with a superior one. The severity of the consequences associated with making type I and II errors should inform the probability with which clients are comfortable making them.</p>
<p>We typically control the probability of making a type I error by choosing a significance level <span class="math inline">\(\alpha\)</span> for the hypothesis test. We reject <span class="math inline">\(H_0\)</span> if the corresponding <span class="math inline">\(p\)</span>-value is less than <span class="math inline">\(\alpha\)</span>. For a point null hypothesis (e.g. <span class="math inline">\(H_0: \mu = 0\)</span>), the <span class="math inline">\(p\)</span>-value takes values of less than <span class="math inline">\(\alpha\)</span> with probability <span class="math inline">\(\alpha\)</span> when <span class="math inline">\(H_0\)</span> is true. Therefore, the significance level <span class="math inline">\(\alpha\)</span> is equal to the probability of making a type I error. Controlling the probability of making a type I error is slightly more complicated when the null hypothesis is not a point null hypothesis (e.g. <span class="math inline">\(H_0: \mu \ge 0\)</span>); in this case, there is more than one value for <span class="math inline">\(\mu\)</span> such that the null hypothesis would be true. In these situations, the significance level <span class="math inline">\(\alpha\)</span> determines the size of the hypothesis test. For <span class="math inline">\(H_0: \mu \ge 0\)</span>, let <span class="math inline">\(\Omega_0 = \{\mu : H_0 ~\text{is true} \}\)</span>. The size of the test is then</p>
<p><span class="math display">\[\text{sup}_{\mu^* \in \Omega_0}~Pr( H_0 ~\text{is rejected} ~| ~\mu^* ~\text{is the true parameter value}).\]</span><br />
Thus, the size of the test is the maximum probability of making a type I error over the entire null hypothesis space <span class="math inline">\(\Omega_0\)</span>. If we use a significance level of <span class="math inline">\(\alpha\)</span> for the <span class="math inline">\(p\)</span>-value when conducting a hypothesis test, the size of the test is typically also equal to <span class="math inline">\(\alpha\)</span>. In many situations, the size of the test is equal to the probability of making a type I error at some boundary point of <span class="math inline">\(\Omega_0\)</span>. For this example, that means that our probability of making a type I error might be much lower than the size of the test for certain true <span class="math inline">\(\mu\)</span> values. For instance, the probability of making a type I error may be equal to <span class="math inline">\(\alpha\)</span> on the boundary <span class="math inline">\(\mu = 0\)</span>, but it may be much less than <span class="math inline">\(\alpha\)</span> if the true, unknown value for <span class="math inline">\(\mu\)</span> is such that <span class="math inline">\(\mu &gt;&gt; 0\)</span>.</p>
<p>We typically control the probability of making a type II error when choosing the sample size for the study. We often let <span class="math inline">\(\beta\)</span> be the probability of making a type II error and define the power of a hypothesis test as 1 - <span class="math inline">\(\beta\)</span>. Ideally, we want the power of a hypothesis test to be high. In general, the power of a hypothesis test can be made larger by increasing the sample size. The power of a test depends on the size of the effect that we would like to be able to detect. Effect size is discussed in more detail in Section <a href="introduction-to-sample-size-determination.html#samp-effect-size">7.1.3</a>. The effect size can generally been seen as the magnitude of the departure from the null hypothesis. Let’s reconsider the null hypothesis <span class="math inline">\(H_0: \mu_1 \ge \mu_2\)</span>. If <span class="math inline">\(\mu_2 = \mu_1 + \epsilon\)</span> for some small <span class="math inline">\(\epsilon &gt; 0\)</span>, then we may require a lot of data gather enough evidence to reject the null hypothesis. However, if <span class="math inline">\(\mu_2 &gt;&gt; \mu_1\)</span>, we may not require much data to reject the null hypothesis. As such, effect size is an important consideration for sample size determination.</p>
</div>
<div id="samp-effect-size" class="section level3 hasAnchor" number="7.1.3">
<h3><span class="header-section-number">7.1.3</span> Effect Size<a href="introduction-to-sample-size-determination.html#samp-effect-size" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Generally, the effect size can be seen as the magnitude of the departure from the null hypothesis. It follows that larger departures (effect sizes) should be easier to detect (i.e., we can detect them using smaller samples). We often assume that the data are approximately normal (an appropriate transformation may need to be applied). In this case, we can assume that the observed data <span class="math inline">\(y_1,...,y_n\)</span> are such that <span class="math inline">\(Y_i \sim N(\mu, \sigma^2)\)</span> for <span class="math inline">\(i=1,...,n\)</span> independently. It is often of interest to test the null hypothesis <span class="math inline">\(H_0: \mu = \mu_0\)</span>. For this hypothesis test, the effect size would typically be given by
<span class="math display">\[d = \frac{\mu - \mu_0}{\sigma}.\]</span>
We discuss this further in Section <a href="introduction-to-sample-size-determination.html#samp-common-models">7.2</a>, but we often need to guess the value of <span class="math inline">\(\sigma\)</span> to conduct the sample size calculation. For a two-sided hypothesis test, the effect size <span class="math inline">\(d\)</span> can be positive or negative. Therefore, if the unknown, true value of <span class="math inline">\(\mu\)</span> is much larger or smaller than <span class="math inline">\(\mu_0\)</span>, we should have greater probability of rejecting the null hypothesis for smaller samples. If we would instead like to conduct a one-sided hypothesis test, we need to more carefully consider the sign of the effect. For instance, we may want to test the null hypothesis <span class="math inline">\(H_0: \mu \le \mu_0\)</span>. In this scenario, it is not seen as a departure from the null hypothesis when <span class="math inline">\(\mu &lt;&lt; \mu_0\)</span>. Therefore, we should only consider effect sizes <span class="math inline">\(d &gt; 0\)</span> when selecting a sample size for the study.</p>
<p>The effect size may also be referred to as Cohen’s <span class="math inline">\(d\)</span> <span class="citation">(<a href="#ref-cohen" role="doc-biblioref">Cohen 2013</a>)</span>, particularly in scenarios where we want to compare two means using their standardized difference. In these scenarios, our null hypothesis of interest is typically <span class="math inline">\(H_0: \mu_1 = \mu_2\)</span>, and the corresponding effect size is
<span class="math display">\[d = \frac{\mu_1 - \mu_2}{\sigma}.\]</span></p>
<p>For the purposes of sample size determination, it is often assumed that the variances for the two normal populations are unknown but the same for both groups. That is, we assume that <span class="math inline">\(Y_{1j} \sim N(\mu_1, \sigma^2)\)</span> for <span class="math inline">\(j = 1,...,n_1\)</span> and <span class="math inline">\(Y_{2j} \sim N(\mu_2, \sigma^2)\)</span> for <span class="math inline">\(j = 1,...,n_2\)</span>. This assumption is typically made for two reasons. First, it simplifies the sample size calculation; we can sometimes compute the sample size that will achieve the desired power for the study using an analytical formula if we assume the variances are the same. We might need to resort to simulation-based sample size determination (discussed in Section <a href="introduction-to-sample-size-determination.html#samp-sec-sim">7.3</a>) if we do not make this assumption. Second, it is often difficult enough for the client to estimate one value for <span class="math inline">\(\sigma\)</span>. They may not have sufficient information to specify <span class="math inline">\(\sigma_1\)</span> and <span class="math inline">\(\sigma_2\)</span>, different measures of variability for each group. If the client does have sufficient information to estimate <span class="math inline">\(\sigma_1\)</span> and <span class="math inline">\(\sigma_2\)</span>, the pooled standard deviation could be used for sample size calculations:
<span class="math display">\[\sigma = \sqrt{\frac{\sigma_1^2}{n_1} + \frac{\sigma_2^2}{n_2}}.\]</span></p>
<p>Although most clients visiting the SCCR may not have sufficient funding to obtain extremely large samples, it is important to note that we are able to detect very small effects when the sample size for the study is very large. As such, it is important to justify that the observed effect sizes are practically – and not just statistically – significant. For instance, we may want to test whether the average final grade in STAT 230 is the same as the average final grade in STAT 231. After collecting (potentially hundreds of) observations from each class, we may estimate the average final grades in STAT 230 and STAT 231 to be 75.1% and 75.3%, respectively. We may have collected enough data to conclude that the difference between the average final grades in the two classes is not exactly 0, but an increase of 0.2% might not be very meaningful. Perhaps a 1% difference in the average final grades is the smallest difference that would be practically important – then this knowledge from the client should inform the effect size used in the sample size calculation. Clients should be prepared to justify that their observed effect sizes are meaningful in the context of their discipline. Simply observing a <span class="math inline">\(p\)</span>-value that is less than the significance level <span class="math inline">\(\alpha\)</span> may be not be enough to guarantee publication. In recent years, certain journals (e.g. <a href="https://www.tandfonline.com/toc/hbas20/current">Basic and Applied Psychology</a> and <a href="https://www.cambridge.org/core/journals/political-analysis">Political Analysis</a>) have actually banned the use of <span class="math inline">\(p\)</span>-values in their journals as a result of <span class="math inline">\(p\)</span>-values being misused in certain situations <span class="citation">(<a href="#ref-wasserstein.lazar" role="doc-biblioref">Wasserstein and Lazar 2016</a>)</span>. Certain journals are now placing more emphasis on precise effect estimation over <span class="math inline">\(p\)</span>-values, which will be discussed briefly in Section <a href="introduction-to-sample-size-determination.html#samp-precision">7.1.5</a>. If applicable, it might be helpful for clients to consider the desired avenue for publication before designing their study.</p>
</div>
<div id="samp-equivalence" class="section level3 hasAnchor" number="7.1.4">
<h3><span class="header-section-number">7.1.4</span> Equivalence Testing<a href="introduction-to-sample-size-determination.html#samp-equivalence" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For certain analyses, clients may want to collect enough data to show that there is no substantial effect. In certain fields, clients may try to do this by computing the <a href="http://daniellakens.blogspot.com/2014/12/observed-power-and-what-to-do-if-your.html">post-hoc power</a> of a study. For instance, if we did not reject the null hypothesis, we might try to use the observed standard deviation (not the value for <span class="math inline">\(\sigma\)</span> estimated prior to conducting the study) to determine what our “post-hoc” power is to detect effects of given sizes. This is not the recommended method for concluding that there is no substantial effect; however, certain journal editors or reviewers may request that a post-hoc power analysis be performed. Equivalence testing <span class="citation">(<a href="#ref-walker.nowacki" role="doc-biblioref">Walker and Nowacki 2011</a>)</span> provides a more statistically sound method to conclude that there is no substantial effect. Equivalence testing requires its own sample size determination procedures.</p>
<p>Equivalence testing aims to conclude that the true effect size lies in the interval <span class="math inline">\((-\delta, \delta)\)</span> for some <span class="math inline">\(\delta &gt; 0\)</span>; this value for <span class="math inline">\(\delta\)</span> is often referred to as the equivalence margin. For instance, a standard hypothesis test may involve the null hypothesis <span class="math inline">\(H_0: \mu_1 = \mu_2\)</span>. Equivalence testing may instead consider the null hypothesis to be <span class="math inline">\(H_0: \{\mu_1 - \mu_2 \le -\delta\}\cup\{\mu_1 - \mu_2 \ge \delta\}\)</span>. If we reject this hypothesis, we can conclude that <span class="math inline">\(\mu_1 - \mu_2 \in (-\delta, \delta)\)</span>. The value of <span class="math inline">\(\delta\)</span> should typically be chosen by the client – based on what would constitute a substantial effect size in the context of their comparison.</p>
<p>Equivalence testing is often carried out using a two one-sided test (TOST) procedure. For the previous example, we would first test the one-sided null hypothesis <span class="math inline">\(H_{01}: \mu_1 - \mu_2 \le -\delta\)</span> and then test the second one-sided null hypothesis <span class="math inline">\(H_{01}: \mu_1 - \mu_2 \ge \delta\)</span>. Let’s again assume that <span class="math inline">\(Y_{1j} \sim N(\mu_1, \sigma^2)\)</span> for <span class="math inline">\(j = 1,...,n_1\)</span> and <span class="math inline">\(Y_{2j} \sim N(\mu_2, \sigma^2)\)</span> for <span class="math inline">\(j = 1,...,n_2\)</span>. If we reject both null hypotheses using one-sided <span class="math inline">\(t\)</span>-tests with significance level <span class="math inline">\(\alpha\)</span>, then we can reject the composite null hypothesis <span class="math inline">\(H_0: \{\mu_1 - \mu_2 \le -\delta\}\cup\{\mu_1 - \mu_2 \ge \delta\}\)</span> with significance level <span class="math inline">\(\alpha\)</span> as well. When conducting sample size determination for equivalence tests, we must specify (i) the estimates for quantities from the previous subsection (<span class="math inline">\(d\)</span>, <span class="math inline">\(\sigma\)</span>, etc.) and (ii) the equivalence margin <span class="math inline">\(\delta\)</span>. <span class="citation">Cohen (<a href="#ref-cohen" role="doc-biblioref">2013</a>)</span> provides some rough context for the standardized effect size <span class="math inline">\(d\)</span>; <span class="math inline">\(d = 0.2\)</span>, <span class="math inline">\(d = 0.5\)</span>, and <span class="math inline">\(d = 0.8\)</span> respectively correspond to small, medium, and large effect sizes. The equivalence margin <span class="math inline">\(\delta\)</span> could be chosen to coincide with Cohen’s advice in the absence of strong subject matter expertise. However, subject matter expertise from the client should be used to choose <span class="math inline">\(\delta\)</span> whenever possible. We often require larger sample sizes to achieve the desired power as the equivalence margin <span class="math inline">\(\delta\)</span> increases to 0.</p>
</div>
<div id="samp-precision" class="section level3 hasAnchor" number="7.1.5">
<h3><span class="header-section-number">7.1.5</span> Precision-Based Sample Size Determination<a href="introduction-to-sample-size-determination.html#samp-precision" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Clients may be planning a study where the objective is not to show the absence or presence of an effect. Instead, they might wish to precisely estimate the size of an effect. A client may have this objective if alternatives to <span class="math inline">\(p\)</span>-values are preferred in their field. They may also be conducting a follow-up study: previous work may be concluded that a non-null effect does exist, and they hope to estimate this effect with greater precision than the original study. In these situations, the sample size may be chosen to bound the length of a confidence interval for the true effect size. The most standard formula for an (approximate) confidence interval is
<span class="math display">\[\hat d \pm z_{1 - \alpha/2}\times s_d/\sqrt{n},\]</span>
where <span class="math inline">\(\hat d\)</span> is the estimate for the effect size <span class="math inline">\(d\)</span> obtained from the data, <span class="math inline">\(z_{1 - \alpha/2}\)</span> is the <span class="math inline">\(1 - \alpha/2\)</span> quantile of the standard normal distribution, and <span class="math inline">\(s_d\)</span> is the estimated standard deviation of the effect size. In certain situations, it may be more appropriate to use a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(\nu\)</span> degrees of freedom instead of a normal distribution, or we may wish to consider a non-symmetric confidence interval. In this subsection, we focus only on the case for the simplest formula given above. In this case, the length of the confidence interval is
<span class="math display">\[2\times z_{1 - \alpha/2}\times s_d/\sqrt{n}.\]</span></p>
<p>To conduct this sample size determination calculation, we must choose a value <span class="math inline">\(\alpha\)</span> such that the confidence interval has the desired coverage <span class="math inline">\(1 - \alpha\)</span>. We must also estimate <span class="math inline">\(\sigma\)</span>, the value for <span class="math inline">\(s_d\)</span> to be used for the purposes of sample size determination. Given <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\sigma\)</span>, the length of the confidence interval is a univariate function of <span class="math inline">\(n\)</span>. Given a target length for the confidence interval <span class="math inline">\(l\)</span>, we can choose the sample size to be
<span class="math display">\[n = \frac{4 \times z_{1 - \alpha/2}^2 \times \sigma^2}{l^2}.\]</span></p>
<p>We note that the sample sizes returned by this approach may be substantially greater than those returned by the more standard sample size calculations to control type I error and power. For instance, if the true value of the effect is <span class="math inline">\(d = 10\)</span>, we may need much less data to conclude that <span class="math inline">\(d \ne 0\)</span> than we would need to precisely estimate the effect. The sample size <span class="math inline">\(n\)</span> is a not a linear function of the target length <span class="math inline">\(l\)</span>. That is, to decrease the length of the confidence interval by a factor of 10, we need to increase the sample size by a factor of <span class="math inline">\(10^2 = 100\)</span>. However, these large sample sizes may be required if we want to estimate effects from the study with the desired level of precision.</p>
</div>
</div>
<div id="samp-common-models" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Sample Size Determination for Common Models<a href="introduction-to-sample-size-determination.html#samp-common-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="pwr-pckg" class="section level3 hasAnchor" number="7.2.1">
<h3><span class="header-section-number">7.2.1</span> The pwr Package<a href="introduction-to-sample-size-determination.html#pwr-pckg" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this subsection, we provide a brief overview of the <a href="https://cran.r-project.org/web/packages/pwr/"><strong>pwr</strong></a> package and its capabilities. The <strong>pwr</strong> package contains several types of functions. The first set of functions involve computing effect sizes for common analyses: <code>cohen.ES()</code>, <code>ES.h()</code>, <code>ES.w1()</code>, and <code>ES.w2()</code>. We will discuss the <code>cohen.ES()</code> function in more detail. This function returns the conventional effect sizes (small, medium, and large) for the tests available in the <strong>pwr</strong> package. This function has two parameters:</p>
<ul>
<li><code>test</code> denotes the statistical test of interest. <code>test = "p"</code> is used for a hypothesis test to compare proportions. <code>test = "t"</code> is used to denote a <span class="math inline">\(t\)</span>-test to compare means (one-sample, two-sample, or paired samples). <code>test = "r"</code> is used for a hypothesis test to compare correlations. <code>test = "anov"</code> is used to denote balanced one-way analysis of variance (ANOVA) tests. <code>test = "chisq"</code> is used to denote <span class="math inline">\(\chi^2\)</span> tests for goodness of fit or association between variables. Lastly, <code>test = "f2"</code> is used for a hypothesis test that considers the <span class="math inline">\(R^2\)</span> statistic from a general linear model.</li>
<li><code>size</code> denotes the effect size. It takes one of three values: <code>"small"</code>, <code>"medium"</code>, or <code>"large"</code>.</li>
</ul>
<p>This function is helpful because you do not need to memorize the conventional effect sizes for the common statistical analyses listed above. The following R code shows what this function outputs for a medium effect corresponding to a balanced one-way ANOVA test.</p>
<div class="sourceCode" id="cb457"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb457-1"><a href="introduction-to-sample-size-determination.html#cb457-1" aria-hidden="true" tabindex="-1"></a>(medium.ANOVA <span class="ot">&lt;-</span> <span class="fu">cohen.ES</span>(<span class="at">test=</span><span class="st">&quot;anov&quot;</span>, <span class="at">size=</span><span class="st">&quot;medium&quot;</span>))</span></code></pre></div>
<pre><code>## 
##      Conventional effect size from Cohen (1982) 
## 
##            test = anov
##            size = medium
##     effect.size = 0.25</code></pre>
<p>The effect size itself can be returned directly using the following code. This effect size can be used as an input value for many of the other functions in the <strong>pwr</strong> package.</p>
<div class="sourceCode" id="cb459"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb459-1"><a href="introduction-to-sample-size-determination.html#cb459-1" aria-hidden="true" tabindex="-1"></a>medium.ANOVA<span class="sc">$</span>effect.size</span></code></pre></div>
<pre><code>## [1] 0.25</code></pre>
<p>The remaining functions in the <strong>pwr</strong> package facilitate power analysis for common statistical analyses: <code>pwr.2p.test()</code>, <code>pwr.2p2n.test()</code>, <code>pwr.anova.test()</code>, <code>pwr.chisq.test()</code>, <code>pwr.f2.test()</code>, <code>pwr.norm.test()</code>, <code>pwr.norm.test()</code>, <code>pwr.p.test()</code>, <code>pwr.r.test()</code>, <code>pwr.t.test()</code>, and <code>pwr.t2n.test()</code>. The functions with <code>2n</code> in their names allow for power analysis will unequal sample sizes; the other functions force the sample sizes to be the same in each group. We will discuss some of these functions in greater detail later in this section (after introducing <a href="https://www.psychologie.hhu.de/arbeitsgruppen/allgemeine-psychologie-und-arbeitspsychologie/gpower.html">G<span class="math inline">\(^*\)</span>Power</a>). We note that power curves can be plotted for many of these analyses using the standard <code>plot()</code> function. This will also be discussed later in this section.</p>
</div>
<div id="gpower-software" class="section level3 hasAnchor" number="7.2.2">
<h3><span class="header-section-number">7.2.2</span> G*Power Software<a href="introduction-to-sample-size-determination.html#gpower-software" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><a href="https://www.psychologie.hhu.de/arbeitsgruppen/allgemeine-psychologie-und-arbeitspsychologie/gpower.html">G<span class="math inline">\(^*\)</span>Power</a> is a free sample size determination software developed by Heinrich Heine University Düsseldorf in Germany. G<span class="math inline">\(^*\)</span>Power is more comprehensive than the <strong>pwr</strong> package in R. Moreover, the <a href="https://uofwaterloo.sharepoint.com/:u:/r/sites/tm-arts-sccr-InternalGeneral/Shared%20Documents/Internal%20General/S22_Sample_Size/GPower_Manual.url?csf=1&amp;web=1">G<span class="math inline">\(^*\)</span>Power user manual</a> is more detailed than the documentation for the <strong>pwr</strong> package in R. Although neither G<span class="math inline">\(^*\)</span>Power nor the <strong>pwr</strong> package offer complete functionality for sample size determination, they offer a good starting point for common statistical analyses. The interface for G<span class="math inline">\(^*\)</span>Power might be easier for clients to use, particularly those who do not have much experience with R. However, if the client is already familiar with with R and their desired analysis is supported by the <strong>pwr</strong> package, then the <strong>pwr</strong> pacakge may be the more suitable choice.</p>
<p>G<span class="math inline">\(^*\)</span>Power supports statistical power analyses for many different statistical tests of the <span class="math inline">\(F\)</span>-test family, the <span class="math inline">\(t\)</span>-test family, <span class="math inline">\(\chi^2\)</span>-test family, <span class="math inline">\(z\)</span>-test family, and even some exact and nonparametric tests. G<span class="math inline">\(^*\)</span>Power provides both effect size calculators and graphics options. G<span class="math inline">\(^*\)</span>Power offers five different types of statistical power analysis. First, it supports a priori analysis, where the sample size <span class="math inline">\(N\)</span> is computed as a function of power level <span class="math inline">\(1 - \beta\)</span>, significance level <span class="math inline">\(\alpha\)</span>, and the to-be-detected population effect size. This is the most common type of power analysis. Second, it supports compromise power analysis, where both <span class="math inline">\(1 - \alpha\)</span> and <span class="math inline">\(\beta\)</span> are computed as functions of the effect size, <span class="math inline">\(N\)</span>, and an error probability ratio <span class="math inline">\(q = \beta/\alpha\)</span>. Third, it supports criterion power analysis, where the significance level <span class="math inline">\(\alpha\)</span> is chosen to obtain the desired power <span class="math inline">\(1 - \beta\)</span> for a given effect size and <span class="math inline">\(N\)</span>. Fourth, it supports post-hoc poweranalysis, where <span class="math inline">\(1 - \beta\)</span> is computed as a function of <span class="math inline">\(\alpha\)</span>, the observed population effect size and <span class="math inline">\(N\)</span>. This type of power analysis may not be recommended. Finally, it supports sensitivity power analysis, where the population effect size is computed as a function of <span class="math inline">\(\alpha\)</span>, power <span class="math inline">\(1 - \beta\)</span>, and <span class="math inline">\(N\)</span>. Sensitivity analysis can be helpful to gauge how sensitive the sample size recommendation is to the effect size (which is to be observed). In situations where the sample size recommendation is very sensitive to the to-be-observed population effect size, it might be best to consider a conservative sample size. This chapter focuses on a priori power analysis.</p>
<p>With G<span class="math inline">\(^*\)</span>Power, one can use dropdown menus to choose the type of power analysis (typically a priori), the family of test (e.g. <span class="math inline">\(F\)</span>-test, <span class="math inline">\(t\)</span>-test, etc.), and the statistical model (e.g. <span class="math inline">\(t\)</span>-test to compare correlations, <span class="math inline">\(t\)</span>-test to compares means, etc.). For a priori power analyses, one will typically need to choose an effect size, <span class="math inline">\(\alpha\)</span>, and desired power <span class="math inline">\(1 - \beta\)</span> to complete the sample size calculation and return a suitable sample size. We discuss how to do this for several common statistical models in the following subsections.</p>
</div>
<div id="samp-ex-ANOVA" class="section level3 hasAnchor" number="7.2.3">
<h3><span class="header-section-number">7.2.3</span> Sample Size Determination for Balanced One-Way ANOVA<a href="introduction-to-sample-size-determination.html#samp-ex-ANOVA" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this subsection, we focus on the fixed effects one-way ANOVA test. It tests whether there are any differences between the means <span class="math inline">\(\mu_i\)</span> of <span class="math inline">\(k \ge 2\)</span> normally distributed random variables each with common variance <span class="math inline">\(\sigma\)</span>. As such, one-way ANOVA can be viewed as an extension of the two group <span class="math inline">\(t\)</span>-test for a difference of means to more than two groups.</p>
<p>The null hypothesis is that all <span class="math inline">\(k\)</span> group means are identical
<span class="math display">\[H_0: \mu_1 = \mu_2 = ... = \mu_k\]</span>
The alternative hypothesis <span class="math inline">\(H_A\)</span> states that at least two of the <span class="math inline">\(k\)</span> means differ. That is, <span class="math inline">\(H_A\)</span> is such that <span class="math inline">\(H_A : \mu_i \ne \mu_j\)</span>, for at least
one pair <span class="math inline">\(i \ne j\)</span> with <span class="math inline">\(1 \le i, j \le k\)</span>.</p>
<p>For one-way ANOVA, the effect size is <span class="math inline">\(f = \sigma_m/\sigma\)</span>, where <span class="math inline">\(\sigma_m\)</span> is the standard deviation of the group means <span class="math inline">\(\mu_i\)</span> for <span class="math inline">\(i = 1, ..., k\)</span> and <span class="math inline">\(\sigma\)</span> the common standard deviation <em>within</em> each of the <span class="math inline">\(k\)</span> groups. Therefore, <span class="math inline">\(f\)</span> may be difficult to choose directly; however, it can be computed directly if we know the number of groups <span class="math inline">\(k\)</span>, the common within-group standard deviation <span class="math inline">\(\sigma\)</span> and a table of <span class="math inline">\((\mu_i, n_i)\)</span> values for <span class="math inline">\(i = 1,...,k\)</span>. These numbers may be easier to estimate for clients. G<span class="math inline">\(^*\)</span>Power facilitates this process using their application, and this process is described in more detail on page 24 in the <a href="https://uofwaterloo.sharepoint.com/:u:/r/sites/tm-arts-sccr-InternalGeneral/Shared%20Documents/Internal%20General/S22_Sample_Size/GPower_Manual.url?csf=1&amp;web=1">G<span class="math inline">\(^*\)</span>Power user manual</a>. After users enter the number of groups <span class="math inline">\(k\)</span> and common standard deviation <span class="math inline">\(\sigma\)</span>, an Excel-type table appears where users can enter the anticipated means <span class="math inline">\(\mu_i\)</span> and sample sizes <span class="math inline">\(n_i\)</span> for each group <span class="math inline">\(i = 1, ..., k\)</span>. G<span class="math inline">\(^*\)</span>Power then returns the corresponding effect size <span class="math inline">\(f\)</span>. Users are also free to use the conventional effect sizes for one-way ANVOA as determined by <span class="citation">Cohen (<a href="#ref-cohen" role="doc-biblioref">2013</a>)</span>: <span class="math inline">\(f =\)</span> 0.1 for a small effect, 0.25 for a medium effect, and 0.4 for a large effect.</p>
<p>We now consider the following example. We suppose that we would like to compare 10 groups, and we expect to observe a “medium” effect size ( <span class="math inline">\(f\)</span> = .25). We now use the <code>pwr.anova.test()</code> function in the <strong>pwr</strong> package to determine how many observations we need in each group with <span class="math inline">\(\alpha\)</span> = 0.05 to achieve a power of 0.95. This example is also provided in the <a href="https://uofwaterloo.sharepoint.com/:u:/r/sites/tm-arts-sccr-InternalGeneral/Shared%20Documents/Internal%20General/S22_Sample_Size/GPower_Manual.url?csf=1&amp;web=1">G<span class="math inline">\(^*\)</span>Power user manual</a>, so we will be able to compare the results from the two programs. The following R code conducts the sample size determination calculation for this example.</p>
<div class="sourceCode" id="cb461"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb461-1"><a href="introduction-to-sample-size-determination.html#cb461-1" aria-hidden="true" tabindex="-1"></a>(p.anova <span class="ot">&lt;-</span> <span class="fu">pwr.anova.test</span>(<span class="at">k=</span><span class="dv">10</span>, <span class="at">f =</span> <span class="fl">0.25</span>, <span class="at">power=</span><span class="fl">0.95</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>))</span></code></pre></div>
<pre><code>## 
##      Balanced one-way analysis of variance power calculation 
## 
##               k = 10
##               n = 38.59793
##               f = 0.25
##       sig.level = 0.05
##           power = 0.95
## 
## NOTE: n is number in each group</code></pre>
<p>After rounding the sample size up to the nearest integer, we determine that we require 39 observations per group for this example. This is the same sample size recommendation returned by G<span class="math inline">\(^*\)</span>Power. For a given sample size determination scenario, we can return a power curve using the standard <code>plot()</code> function in R (on an object to which the power calculation was saved) as demonstrated below in Figure <a href="introduction-to-sample-size-determination.html#fig:pwr1">7.1</a>.</p>
<div class="sourceCode" id="cb463"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb463-1"><a href="introduction-to-sample-size-determination.html#cb463-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p.anova)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:pwr1"></span>
<img src="topics_in_consulting_files/figure-html/pwr1-1.png" alt="Visualization of power curve for one-way ANOVA example" width="672" />
<p class="caption">
Figure 7.1: Visualization of power curve for one-way ANOVA example
</p>
</div>
<p>Figure <a href="introduction-to-sample-size-determination.html#fig:pwr1">7.1</a> depicts the power of the one-way ANOVA test as a function of the sample size per group <span class="math inline">\(n\)</span>. Similar graphics can also be produced in G<span class="math inline">\(^*\)</span>Power. Although G<span class="math inline">\(^*\)</span>Power allows the effect size <span class="math inline">\(f\)</span> to be estimated using a table of <span class="math inline">\((\mu_i, n_i)\)</span> values where the <span class="math inline">\(n_i\)</span> values are not forced to be equal for all <span class="math inline">\(i = 1, ...,k\)</span>, G<span class="math inline">\(^*\)</span>Power provides a common sample size recommendation for each group. The one-way ANOVA is called a balanced one-way ANOVA when <span class="math inline">\(n_1 = ... = n_k = n\)</span>. Finally, we note that neither the <strong>pwr</strong> package nor G<span class="math inline">\(^*\)</span>Power provide functionality for sample size determination for one-way ANOVA when the within-group variance is not the same for all groups. We discuss how to conduct sample size calculations for such scenarios in Section <a href="introduction-to-sample-size-determination.html#samp-sec-sim">7.3</a>.</p>
</div>
<div id="samp-ex-mlr" class="section level3 hasAnchor" number="7.2.4">
<h3><span class="header-section-number">7.2.4</span> Sample Size Determination for Multiple Regression Model<a href="introduction-to-sample-size-determination.html#samp-ex-mlr" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this subsection, we focus on an omnibus <span class="math inline">\(F\)</span>-test for multiple regression where we consider the deviation of <span class="math inline">\(R^2\)</span> (the coefficient of determination) from 0. The multiple linear regression model explains the relationships between a dependent variable <span class="math inline">\(Y\)</span> and <span class="math inline">\(p\)</span> independent variables <span class="math inline">\(X_1\)</span>, …, <span class="math inline">\(X_p\)</span>. The type of multiple linear regression model explored in this subsection assumes that the independent variables are fixed. Thus, we consider a model for the response <span class="math inline">\(Y\)</span> that is conditional on the values of the independent variables. Therefore, we assume that given <span class="math inline">\(N\)</span> (<span class="math inline">\(\boldsymbol{Y}\)</span>, <span class="math inline">\(\boldsymbol{X}\)</span>)observations,
<span class="math display">\[\boldsymbol{Y} = \boldsymbol{X}\boldsymbol{\beta} + \boldsymbol{\varepsilon},\]</span>
where <span class="math inline">\(\boldsymbol{X} = [1, \boldsymbol{X}_1, ..., \boldsymbol{X}_p]\)</span> is a <span class="math inline">\(N \times (p + 1)\)</span> matrix of a constant term and fixed, known predictor <span class="math inline">\(\boldsymbol{X}_i\)</span>. Moreover, <span class="math inline">\(\boldsymbol{\beta}\)</span> is a column vector of <span class="math inline">\(p + 1\)</span> regression coefficients. The column vector <span class="math inline">\(\boldsymbol{\varepsilon}\)</span> of length <span class="math inline">\(N\)</span> contains the error terms such that <span class="math inline">\(\varepsilon_i \sim N(0, \sigma^2)\)</span> for <span class="math inline">\(i = 1, ..., N\)</span>.</p>
<p>G<span class="math inline">\(^*\)</span>Power supports power analyses for the test that the proportion of variance of the dependent variable <span class="math inline">\(Y\)</span> explained by a set of predictors <span class="math inline">\(B = \{1, ..., p\}\)</span>, denoted <span class="math inline">\(R^2_{Y\cdot B}\)</span>, is equal to 0. The corresponding null and alternative hypotheses are
<span class="math display">\[H_0: R^2_{Y\cdot B} = 0 ~~~\text{vs.}~~~ H_A: R^2_{Y\cdot B} &gt; 0.\]</span>
Under the null hypothesis, the appropriate test statistic follows an <span class="math inline">\(F\)</span> distribution with <span class="math inline">\(p\)</span> degrees of freedom in the numerator and <span class="math inline">\(N - (p+1)\)</span> degrees of freedom in the denominator.</p>
<p>For this procedure, the effect size <span class="math inline">\(f^2\)</span> is such that <span class="math inline">\(f^2 = V_S/V_E\)</span>, where <span class="math inline">\(V_S\)</span> is the proportion of variance explained by the set of predictors <span class="math inline">\(B\)</span>, and <span class="math inline">\(V_E\)</span> is the proportion of residual variance not explained by the predictors. That is, <span class="math inline">\(V_S + V_E = 1\)</span>. For the multiple linear regression scenario given above, the proportion of variance explained by the set of predictors <span class="math inline">\(B\)</span> is given by <span class="math inline">\(R^2_{Y\cdot B}\)</span> and the residual variance is given by <span class="math inline">\(V_E = 1 - R^2_{Y\cdot B}\)</span>. It follows that
<span class="math display">\[f^2 = \frac{R^2_{Y\cdot B}}{1 - R^2_{Y\cdot B}}.\]</span></p>
<p>G<span class="math inline">\(^*\)</span>Power provides functionality to choose an effect size <span class="math inline">\(f^2\)</span> using estimated correlations between the independent variables and the estimated correlations between the dependent variable <span class="math inline">\(Y\)</span> and each independent variable. After users enter the number of independent variables <span class="math inline">\(p\)</span> in their model, two Excel-type table appear. The first table is of dimension <span class="math inline">\(p \times 1\)</span> and allows users to estimate a correlation coefficient between the response variable <span class="math inline">\(Y\)</span> and each predictor variable. The second table is a matrix of dimension <span class="math inline">\(p \times p\)</span>, where users can estimate correlation coefficients between each pair of independent variables <span class="math inline">\((X_i, X_j)\)</span> such that <span class="math inline">\(i &lt; j\)</span>. We note that the correlation between <span class="math inline">\(X_i\)</span> and itself is 1 and that the correlation coefficient for the pair of variables <span class="math inline">\((X_i, X_j)\)</span> is symmetric in the roles of <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>. After the user inputs these estimated values into the application, G<span class="math inline">\(^*\)</span>Power returns an effect size <span class="math inline">\(f^2\)</span>. This process is explained in more detail on pages 33 and 34 of the <a href="https://uofwaterloo.sharepoint.com/:u:/r/sites/tm-arts-sccr-InternalGeneral/Shared%20Documents/Internal%20General/S22_Sample_Size/GPower_Manual.url?csf=1&amp;web=1">G<span class="math inline">\(^*\)</span>Power user manual</a>. Users are also free to use the conventional effect sizes for the omnibus test for <span class="math inline">\(R^2\)</span> with multiple linear regression as determined by <span class="citation">Cohen (<a href="#ref-cohen" role="doc-biblioref">2013</a>)</span>: <span class="math inline">\(f^2 =\)</span> 0.02 for a small effect, 0.15 for a medium effect, and 0.35 for a large effect.</p>
<p>We now consider the following example. We suppose that we would like to consider a regression model with 5 independent variables, and we have reason to expect an effect size of <span class="math inline">\(f\)</span> = 1/9. This is somewhere between a small and medium effect size. We now use the <code>pwr.f2.test()</code> function in the <strong>pwr</strong> package to determine the power that we have to detect this effect when <span class="math inline">\(\alpha\)</span> = 0.05 and we have <span class="math inline">\(N =\)</span> 95 observations. This example is also provided in the <a href="https://uofwaterloo.sharepoint.com/:u:/r/sites/tm-arts-sccr-InternalGeneral/Shared%20Documents/Internal%20General/S22_Sample_Size/GPower_Manual.url?csf=1&amp;web=1">G<span class="math inline">\(^*\)</span>Power user manual</a>, so we will be able to compare the results from the two programs. The following R code conducts the sample size determination calculation for this example.</p>
<div class="sourceCode" id="cb464"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb464-1"><a href="introduction-to-sample-size-determination.html#cb464-1" aria-hidden="true" tabindex="-1"></a>(p.f2 <span class="ot">&lt;-</span> <span class="fu">pwr.f2.test</span>(<span class="at">u=</span><span class="dv">5</span>, <span class="at">v =</span> <span class="dv">89</span>, <span class="at">f2 =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">9</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>))</span></code></pre></div>
<pre><code>## 
##      Multiple regression power calculation 
## 
##               u = 5
##               v = 89
##              f2 = 0.1111111
##       sig.level = 0.05
##           power = 0.6735858</code></pre>
<p>For the <code>pwr.f2.test()</code> function, <code>u</code> is the degrees of freedom in the numerator, <code>v</code> is the degrees of freedom in the denominator, and <code>f2</code> is the effect size. With these inputs, we estimate the power of the appropriate <span class="math inline">\(F\)</span>-test to be 0.674. This is the same estimated power returned by G<span class="math inline">\(^*\)</span>Power. The <strong>pwr</strong> package does not faciliate plotting power curves for the <code>pwr.f2.test()</code> function. This relatively simple multiple linear regression example exhausts the <strong>pwr</strong> package’s sample size determination capabilities. G<span class="math inline">\(^*\)</span>Power provides much more functionality for sample size determination with regression models, including sample size calculations for comparing a single regression coefficient to a fixed value, sample size calculations for comparing the equality of two regression coefficients, and sample size calculations for considering the increase in the <span class="math inline">\(R^2\)</span> value that arises from using a more complicated multiple linear regression model. These scenarios are described in the <a href="https://uofwaterloo.sharepoint.com/:u:/r/sites/tm-arts-sccr-InternalGeneral/Shared%20Documents/Internal%20General/S22_Sample_Size/GPower_Manual.url?csf=1&amp;web=1">G<span class="math inline">\(^*\)</span>Power user manual</a>.</p>
</div>
<div id="samp-ex-t" class="section level3 hasAnchor" number="7.2.5">
<h3><span class="header-section-number">7.2.5</span> Sample Size Determination to Compare Two Means (Unknown, Common Variance)<a href="introduction-to-sample-size-determination.html#samp-ex-t" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this subsection, we focus on a third and final scenario for sample size determination with the <strong>pwr</strong> package and G<span class="math inline">\(^*\)</span>Power. For this scenario, we consider a <span class="math inline">\(t\)</span>-test to gauge the equality of two independent populations means <span class="math inline">\(\mu_1\)</span> (corresponding to group 1) and <span class="math inline">\(\mu_2\)</span> (corresponding to group 2). The data consist of two samples of size <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> from two independent and normally distributed populations. For this test, we assume that the true standard deviations in the two populations are unknown and will be estimated from the data. The null and alternative hypotheses of this <span class="math inline">\(t\)</span>-test are
<span class="math display">\[H_0: \mu_1 = \mu_2 ~~~\text{vs.}~~~ H_A: \mu_1 \ne \mu_2.\]</span>
We use a two-sided test if there is no restriction on the sign of the deviation of the alternative hypothesis <span class="math inline">\(H_A\)</span>. Otherwise, we use the one-sided test.</p>
<p>As mentioned earlier, the effect size in this scenario is
<span class="math display">\[d = \frac{\mu_1 - \mu_2}{\sigma},\]</span>
where <span class="math inline">\(\sigma\)</span> is the common standard deviation for the two groups of normal data. <span class="citation">Cohen (<a href="#ref-cohen" role="doc-biblioref">2013</a>)</span> suggested using <span class="math inline">\(d =\)</span> 0.2 for a small effect, 0.5 for a medium effect, and 0.8 for a large effect. However, the effect size <span class="math inline">\(d\)</span> for this situation is more interpretable than the effect sizes for the previous two scenarios considered. As such, clients may have substantial enough information to choose an effect size for the sample size calculation.</p>
<p>We now consider the following example. We suppose that we would like to compare two means, and we expect to observe a “medium” effect size ( <span class="math inline">\(d\)</span> = 0.5). We want to perform a two-sided hypothesis test to consider the equality of <span class="math inline">\(\mu_1\)</span> and <span class="math inline">\(\mu_2\)</span>. We now use the <code>pwr.t.test()</code> function in the <strong>pwr</strong> package to determine how many observations we need in each group with <span class="math inline">\(\alpha\)</span> = 0.05 to achieve a power of 0.8. The following R code conducts the sample size determination calculation for this example.</p>
<div class="sourceCode" id="cb466"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb466-1"><a href="introduction-to-sample-size-determination.html#cb466-1" aria-hidden="true" tabindex="-1"></a>(p.t <span class="ot">&lt;-</span> <span class="fu">pwr.t.test</span>(<span class="at">d=</span><span class="fl">0.5</span>, <span class="at">power=</span><span class="fl">0.8</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">type =</span> <span class="st">&quot;two.sample&quot;</span>, </span>
<span id="cb466-2"><a href="introduction-to-sample-size-determination.html#cb466-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>))</span></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 63.76561
##               d = 0.5
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<p>For the <code>pwr.t.test()</code> function, <code>type</code> can take a value of either <code>"two-sample"</code>, <code>"one-sample"</code>, or <code>"paired"</code>. Moreover, <code>alternative</code> can take a value of <code>"two.sided"</code>, <code>"less"</code>, or <code>"greater"</code> – where <code>"less"</code> and <code>"greater"</code> should correspond to negative and positive values of <code>d</code>, respectively. After rounding the sample size up to the nearest integer, we determine that we require 64 observations per group for this example. For this example, we can return a power curve using the standard <code>plot()</code> function in R as demonstrated below in Figure <a href="introduction-to-sample-size-determination.html#fig:pwr3">7.2</a>.</p>
<div class="sourceCode" id="cb468"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb468-1"><a href="introduction-to-sample-size-determination.html#cb468-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p.t)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:pwr3"></span>
<img src="topics_in_consulting_files/figure-html/pwr3-1.png" alt="Visualization of power curve for two-sample t-test example" width="672" />
<p class="caption">
Figure 7.2: Visualization of power curve for two-sample t-test example
</p>
</div>
<p>Figure <a href="introduction-to-sample-size-determination.html#fig:pwr3">7.2</a> depicts the power of the two-sample <span class="math inline">\(t\)</span>-test as a function of the sample size per group <span class="math inline">\(n\)</span>. Similar graphics can also be produced in G<span class="math inline">\(^*\)</span>Power. The two-sample <span class="math inline">\(t\)</span>-test functions in the <strong>pwr</strong> package force the standard deviation <span class="math inline">\(\sigma\)</span> in the two groups to be the same. G<span class="math inline">\(^*\)</span>Power does allow for sample size calculations where the standard deviations are not the same for the two groups (i.e., <span class="math inline">\(\sigma_1 \ne \sigma_2\)</span>) for the case when <span class="math inline">\(n_1 = n_2\)</span>. However, this sample size determination calculation still assumes that <a href="https://en.wikipedia.org/wiki/Student%27s_t-test">Student’s <em>t</em>-test</a> will be used, and this test assumes that the standard deviation is the same in both groups. Therefore, this sample size calculation facilitated by G<span class="math inline">\(^*\)</span>Power is an approximate calculation. When <span class="math inline">\(\sigma_1 \ne \sigma_2\)</span>, it is more appropriate to use <a href="https://en.wikipedia.org/wiki/Welch%27s_t-test">Welch’s <em>t</em>-test</a>. Most free sample size determination software solutions do not offer this functionality, but we discuss how to conduct sample size calculations for this particular scenario in Section <a href="introduction-to-sample-size-determination.html#samp-sec-sim">7.3</a>. We note that both the <strong>pwr</strong> package in R and G<span class="math inline">\(^*\)</span>Power offer more sample size determination functionality than explored in the previous three examples. More details about this additional functionality can be found in the documentation for these software solutions.</p>
</div>
<div id="samp-TOSTER" class="section level3 hasAnchor" number="7.2.6">
<h3><span class="header-section-number">7.2.6</span> The TOSTER Package<a href="introduction-to-sample-size-determination.html#samp-TOSTER" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To conclude this subsection, we discuss the <a href="https://cran.r-project.org/web/packages/TOSTER/"><strong>TOSTER</strong></a> package, which facilitates sample size calculations for equivalence tests when the TOST procedure is carried out using two one-sided <span class="math inline">\(t\)</span>-tests. This package facilitates sample size determination for two-sample, one-sample, and paired <span class="math inline">\(t\)</span>-tests, but we will focus on the two-sample case in this subsection. For the two-sample case, the <strong>TOSTER</strong> package requires that we make the assumption that the standard deviation <span class="math inline">\(\sigma\)</span> is the same in both groups. For this scenario and a given equivalence margin <span class="math inline">\(\delta\)</span>, our null and alternative hypotheses are
<span class="math display">\[H_0: \{\mu_1 - \mu_2 \le -\delta\}\cup\{\mu_1 - \mu_2 \ge \delta\} ~~~\text{vs.}~~~ H_A: -\delta &lt; \mu_1 - \mu_2 &lt; \delta.\]</span></p>
<p>For this sample size determination calculation, we need to choose a values for the equivalence margin <span class="math inline">\(\delta\)</span>, the significance level <span class="math inline">\(\alpha\)</span>, and the power <span class="math inline">\(1 - \beta\)</span>; we must also estimate a value for the common standard deviation <span class="math inline">\(\sigma\)</span> and estimate a value for <span class="math inline">\(\mu_1 - \mu_2\)</span>. The <code>power_T_tost()</code> function allows us to specify the true effect via the raw (unstandardized) effect. The <code>power_t_TOST()</code> function has the following arguments:</p>
<ul>
<li><code>delta</code>: the value for <code>delta</code> is <em>not</em> the value specified for the equivalence margin <span class="math inline">\(\delta\)</span>. Instead, it is the value that we anticipate to observe for <span class="math inline">\(\mu_1 - \mu_2\)</span>. We can specify <code>delta</code> using the anticipated difference between <span class="math inline">\(\mu_1\)</span> and <span class="math inline">\(\mu_2\)</span>. It is important to specify this difference because the power of the equivalence test is going to depend on how close the true value of <span class="math inline">\(\mu_1 - \mu_2\)</span> is to either endpoint of the interval <span class="math inline">\((-\delta, \delta)\)</span>. If we anticipate that <span class="math inline">\(\mu_1 = \mu_2\)</span>, we may need less data to conclude practical equivalence than if <span class="math inline">\(\mu_1 - \mu_2\)</span> is close to <span class="math inline">\(-\delta\)</span> or <span class="math inline">\(\delta\)</span>.</li>
<li><code>sd</code>: the estimated value for the common standard deviation for the two groups.</li>
<li><code>low_eqbound</code>: the lower bound of the region of equivalence. This is typically <span class="math inline">\(-\delta\)</span>, but the <code>power_T_tost()</code> allows for this interval to be asymmetric around 0.</li>
<li><code>high_eqbound</code>: the upper bound of the region of equivalence. This is typically <span class="math inline">\(\delta\)</span>, but the <code>power_T_tost()</code> allows for this interval to be asymmetric around 0.</li>
<li><code>alpha</code>: the significance level for the test.</li>
<li><code>power</code>: the desired power of the equivalence test.</li>
</ul>
<p>We now consider the following example. We suppose that we would like to compare two means, and we anticipate the difference between the two means to be 0.5. We anticipate that each group of data has a standard deviation of 5. Moreover, we define the equivalence margin to be 2 (i.e., it is not of practical importance if the means of the two groups differ by at most 2 in absolute value). We now use the <code>power_t_TOST()</code> function to determine how many observations we need in each group with <span class="math inline">\(\alpha\)</span> = 0.05 to achieve a power of 0.8. The following R code conducts the sample size determination calculation for this example.</p>
<div class="sourceCode" id="cb469"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb469-1"><a href="introduction-to-sample-size-determination.html#cb469-1" aria-hidden="true" tabindex="-1"></a>(p.TOST <span class="ot">&lt;-</span> <span class="fu">power_t_TOST</span>(<span class="at">delta =</span> <span class="fl">0.5</span>, <span class="at">sd =</span> <span class="dv">5</span>, <span class="at">low_eqbound =</span> <span class="sc">-</span><span class="dv">2</span>, <span class="at">high_eqbound =</span> <span class="dv">2</span>, </span>
<span id="cb469-2"><a href="introduction-to-sample-size-determination.html#cb469-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">alpha =</span> <span class="fl">0.05</span>, <span class="at">power =</span> <span class="fl">0.8</span>))</span></code></pre></div>
<pre><code>## 
##      Two-sample TOST power calculation 
## 
##           power = 0.8
##            beta = 0.2
##           alpha = 0.05
##               n = 140.3308
##           delta = 0.5
##              sd = 5
##          bounds = -2, 2
## 
## NOTE: n is number in *each* group</code></pre>
<p>After rounding the sample size up to the nearest integer, we determine that we require 141 observations per group for this example. The <strong>TOSTER</strong> function does not support the plotting of power curves for equivalence tests. These curves must be plotted manually, as discussed in Section <a href="introduction-to-sample-size-determination.html#samp-sec-sim">7.3</a>. The <strong>TOSTER</strong> package only supports basic sample size calculations for equivalence testing, but it is an accessible starting point in terms of software that is freely available.</p>
</div>
</div>
<div id="samp-sec-sim" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Simulation-Based Sample Size Determination<a href="introduction-to-sample-size-determination.html#samp-sec-sim" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="samp-sim-sing" class="section level3 hasAnchor" number="7.3.1">
<h3><span class="header-section-number">7.3.1</span> Computing a Single Power Estimation via Simulation<a href="introduction-to-sample-size-determination.html#samp-sim-sing" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If the model that we intend to use to analyze the data from the study is not supported by the <strong>pwr</strong> package in R or G<span class="math inline">\(^*\)</span>Power, we may need to resort to simulation-based sample size determination. Simulation-based sample size determination involves specifying distributions for the data and generating samples of a given size <span class="math inline">\(n\)</span>. These samples of size <span class="math inline">\(n\)</span> can typically be generated using built-in R functions – such as <code>rnorm()</code>, <code>rexp()</code>, <code>rpois()</code>, or <code>rgamma()</code>. For this simulated data, we conduct the hypothesis test of interest and record whether or not we reject the null hypothesis for a specified significance level <span class="math inline">\(\alpha\)</span>. We can repeat this process many times, and the proportion of simulations for which we reject the null hypothesis provides an estimate for the power of the test given the distribution(s) chosen for the data, the significance level <span class="math inline">\(\alpha\)</span>, and the sample size <span class="math inline">\(n\)</span>.</p>
<p>Simulation-based sample size determination can be useful in situations where heteroscedasticity is present (i.e., we have multiple groups of data, and the variance within each group is not the same). In these situations, we may not be able to compute the power of the statistical test using analytical formulas. Moreover, simulation-based sample size determination can also be useful when we would like to use nonparametric hypothesis tests. The <strong>pwr</strong> package does not provide any functionality for samples size calculations with nonparametric tests, and G<span class="math inline">\(^*\)</span>Power offers very limited functionality.</p>
<p>We illustrate how to conduct simulation-based sample size determination using the following example. Let’s assume that we want to conduct a two-sample <span class="math inline">\(t\)</span>-test, but we have reason to believe that the standard deviations from the two groups are not the same. Let’s assume that we want to conduct a two-sided hypothesis test. Let’s further assume that we believe that <span class="math inline">\(Y_{1j} \sim N(0, 1)\)</span> for <span class="math inline">\(j = 1, ..., n_1\)</span> and that <span class="math inline">\(Y_{2j} \sim N(1, 2)\)</span> for <span class="math inline">\(j = 1, ..., n_2\)</span>. As such, we would anticipate using Welch’s <span class="math inline">\(t\)</span>-test to conduct the hypothesis test. The Student’s two-sample <span class="math inline">\(t\)</span>-test leverages a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n_1 + n_2 - 2\)</span> degrees of freedom. However, under the null hypothesis <span class="math inline">\(H_0: \mu_1 = \mu_2\)</span> the Welch’s two-sample <span class="math inline">\(t\)</span>-test has a <span class="math inline">\(t\)</span>-distribution with the degrees of freedom given by
<span class="math display">\[df^* = \dfrac{\left(\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}\right)^2}{\frac{s_1^4}{n_1^2(n_1 -1)} + \frac{s_2^4}{n_2^2(n_2 -1)}},\]</span>
where <span class="math inline">\(s_1^2\)</span> and <span class="math inline">\(s_2^2\)</span> are the observed sample variance for the observations from groups 1 and 2. That is, we do not know the degrees of freedom for the test statistic a priori. This can make it difficult to compute the power of the <span class="math inline">\(t\)</span>-test analytically. The following R code (with comments) shows how to estimate the power of Welch’s <span class="math inline">\(t\)</span>-test in this scenario for <span class="math inline">\(n_1 = n_2 = 50\)</span> and significance level <span class="math inline">\(\alpha = 0.05\)</span> via simulation. This example assumes that the study design is balanced (i.e., <span class="math inline">\(n_1 = n_2\)</span>), but this is certainly not a requirement for simulation-based sample size determination.</p>
<div class="sourceCode" id="cb471"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb471-1"><a href="introduction-to-sample-size-determination.html#cb471-1" aria-hidden="true" tabindex="-1"></a><span class="do">## choose the number of simulation repetitions</span></span>
<span id="cb471-2"><a href="introduction-to-sample-size-determination.html#cb471-2" aria-hidden="true" tabindex="-1"></a>n_sim <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb471-3"><a href="introduction-to-sample-size-determination.html#cb471-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb471-4"><a href="introduction-to-sample-size-determination.html#cb471-4" aria-hidden="true" tabindex="-1"></a><span class="do">## set the significance level for the test</span></span>
<span id="cb471-5"><a href="introduction-to-sample-size-determination.html#cb471-5" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb471-6"><a href="introduction-to-sample-size-determination.html#cb471-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb471-7"><a href="introduction-to-sample-size-determination.html#cb471-7" aria-hidden="true" tabindex="-1"></a><span class="do">## set the sample size for each group</span></span>
<span id="cb471-8"><a href="introduction-to-sample-size-determination.html#cb471-8" aria-hidden="true" tabindex="-1"></a>n1 <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb471-9"><a href="introduction-to-sample-size-determination.html#cb471-9" aria-hidden="true" tabindex="-1"></a>n2 <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb471-10"><a href="introduction-to-sample-size-determination.html#cb471-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb471-11"><a href="introduction-to-sample-size-determination.html#cb471-11" aria-hidden="true" tabindex="-1"></a><span class="do">## set the anticipated parameters for each group</span></span>
<span id="cb471-12"><a href="introduction-to-sample-size-determination.html#cb471-12" aria-hidden="true" tabindex="-1"></a>mu1 <span class="ot">&lt;-</span> <span class="dv">0</span>; sigma1 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb471-13"><a href="introduction-to-sample-size-determination.html#cb471-13" aria-hidden="true" tabindex="-1"></a>mu2 <span class="ot">&lt;-</span> <span class="dv">1</span>; sigma2 <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb471-14"><a href="introduction-to-sample-size-determination.html#cb471-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb471-15"><a href="introduction-to-sample-size-determination.html#cb471-15" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb471-16"><a href="introduction-to-sample-size-determination.html#cb471-16" aria-hidden="true" tabindex="-1"></a><span class="do">## initialize vector to output results of hypothesis test for simulated data</span></span>
<span id="cb471-17"><a href="introduction-to-sample-size-determination.html#cb471-17" aria-hidden="true" tabindex="-1"></a>reject <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb471-18"><a href="introduction-to-sample-size-determination.html#cb471-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_sim){</span>
<span id="cb471-19"><a href="introduction-to-sample-size-determination.html#cb471-19" aria-hidden="true" tabindex="-1"></a>  <span class="do">## randomly generate simulated data from both groups</span></span>
<span id="cb471-20"><a href="introduction-to-sample-size-determination.html#cb471-20" aria-hidden="true" tabindex="-1"></a>  y1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n1, mu1, sigma1)</span>
<span id="cb471-21"><a href="introduction-to-sample-size-determination.html#cb471-21" aria-hidden="true" tabindex="-1"></a>  y2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n2, mu2, sigma2)</span>
<span id="cb471-22"><a href="introduction-to-sample-size-determination.html#cb471-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb471-23"><a href="introduction-to-sample-size-determination.html#cb471-23" aria-hidden="true" tabindex="-1"></a>  <span class="do">## conduct Welch&#39;s test (i.e., set var.equal = FALSE, which is the default)</span></span>
<span id="cb471-24"><a href="introduction-to-sample-size-determination.html#cb471-24" aria-hidden="true" tabindex="-1"></a>  p.sim <span class="ot">&lt;-</span> <span class="fu">t.test</span>(y1, y2, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>p.value</span>
<span id="cb471-25"><a href="introduction-to-sample-size-determination.html#cb471-25" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb471-26"><a href="introduction-to-sample-size-determination.html#cb471-26" aria-hidden="true" tabindex="-1"></a>  <span class="do">## turn results into binary vector (1 if we reject null hypothesis; 0 otherwise)</span></span>
<span id="cb471-27"><a href="introduction-to-sample-size-determination.html#cb471-27" aria-hidden="true" tabindex="-1"></a>  reject[i] <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(p.sim <span class="sc">&lt;</span> alpha, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb471-28"><a href="introduction-to-sample-size-determination.html#cb471-28" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb471-29"><a href="introduction-to-sample-size-determination.html#cb471-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb471-30"><a href="introduction-to-sample-size-determination.html#cb471-30" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(reject)</span></code></pre></div>
<pre><code>## [1] 0.875</code></pre>
<p>Therefore, we estimate that Welch’s <span class="math inline">\(t\)</span>-test has power of 0.875 to reject the null hypothesis <span class="math inline">\(H_0: \mu_1 = \mu_2\)</span> when <span class="math inline">\(Y_{1j} \sim N(0, 1)\)</span> for <span class="math inline">\(j = 1, ..., n_1\)</span> and that <span class="math inline">\(Y_{2j} \sim N(1, 2)\)</span> for <span class="math inline">\(j = 1, ..., n_2\)</span> for <span class="math inline">\(n_1 = n_2 = 50\)</span> and a signficance level of <span class="math inline">\(\alpha = 0.05\)</span>. For this simulation, we chose <code>n_sim</code> = 1000. This value ensures that the code runs quickly when compiling this document. We would likely want to use a larger value (at least <code>n_sim</code> = 10000) in practice. If we use small values for <code>n_sim</code>, then the estimated power will not be very precise. If <span class="math inline">\(\widehat{pwr}\)</span> is a given estimate for the power of a hypothesis test in a given scenario, then the standard error of this estimate is given by
<span class="math display">\[\sqrt{\frac{\widehat{pwr}(1 - \widehat{pwr})}{n_{sim}}}.\]</span>
Therefore, if we choose <code>n_sim</code> = 10000, then the standard error of the estimate for power is at most 0.005 (this maximum is obtained when <span class="math inline">\(\widehat{pwr} =\)</span> 0.5).</p>
</div>
<div id="samp-est-curve" class="section level3 hasAnchor" number="7.3.2">
<h3><span class="header-section-number">7.3.2</span> Estimating a Power Curve via Simulation<a href="introduction-to-sample-size-determination.html#samp-est-curve" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Both the <strong>pwr</strong> function in R and G<span class="math inline">\(^*\)</span>Power facilitate the creation of power curves in certain scenarios. These power curves can also be estimated via simulation, although this may be a computationally intensive process. The following block of code takes the power estimation code from the previous code block. This function <code>estPower()</code> has eight inputs: the number of simulation repetitions <code>n_sim</code>, the sample sizes for each group <code>n1</code> and <code>n2</code>, the anticipated parameters of the normal distribution for group 1 <code>mu1</code> and <code>sigma1</code>, the anticipated parameters of the normal distribution for group 2 <code>mu2</code> and <code>sigma2</code>, and the significance level <code>alpha</code>. This function can generally be used to conduct power analysis for two-sided Welch <span class="math inline">\(t\)</span>-tests.</p>
<div class="sourceCode" id="cb473"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb473-1"><a href="introduction-to-sample-size-determination.html#cb473-1" aria-hidden="true" tabindex="-1"></a><span class="do">## put the previous code in functional form</span></span>
<span id="cb473-2"><a href="introduction-to-sample-size-determination.html#cb473-2" aria-hidden="true" tabindex="-1"></a>estPower <span class="ot">&lt;-</span> <span class="cf">function</span>(n_sim, n1, n2, mu1, sigma1, mu2, sigma2, alpha){</span>
<span id="cb473-3"><a href="introduction-to-sample-size-determination.html#cb473-3" aria-hidden="true" tabindex="-1"></a>  <span class="do">## initialize vector to output results of hypothesis test for simulated data</span></span>
<span id="cb473-4"><a href="introduction-to-sample-size-determination.html#cb473-4" aria-hidden="true" tabindex="-1"></a>  reject <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb473-5"><a href="introduction-to-sample-size-determination.html#cb473-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_sim){</span>
<span id="cb473-6"><a href="introduction-to-sample-size-determination.html#cb473-6" aria-hidden="true" tabindex="-1"></a>    <span class="do">## randomly generate simulated data from both groups</span></span>
<span id="cb473-7"><a href="introduction-to-sample-size-determination.html#cb473-7" aria-hidden="true" tabindex="-1"></a>    y1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n1, mu1, sigma1)</span>
<span id="cb473-8"><a href="introduction-to-sample-size-determination.html#cb473-8" aria-hidden="true" tabindex="-1"></a>    y2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n2, mu2, sigma2)</span>
<span id="cb473-9"><a href="introduction-to-sample-size-determination.html#cb473-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb473-10"><a href="introduction-to-sample-size-determination.html#cb473-10" aria-hidden="true" tabindex="-1"></a>    <span class="do">## conduct Welch&#39;s test (i.e., set var.equal = FALSE, which is the default)</span></span>
<span id="cb473-11"><a href="introduction-to-sample-size-determination.html#cb473-11" aria-hidden="true" tabindex="-1"></a>    p.sim <span class="ot">&lt;-</span> <span class="fu">t.test</span>(y1, y2, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>p.value</span>
<span id="cb473-12"><a href="introduction-to-sample-size-determination.html#cb473-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb473-13"><a href="introduction-to-sample-size-determination.html#cb473-13" aria-hidden="true" tabindex="-1"></a>    <span class="do">## turn results into binary vector (1 if we reject null hypothesis; 0 otherwise)</span></span>
<span id="cb473-14"><a href="introduction-to-sample-size-determination.html#cb473-14" aria-hidden="true" tabindex="-1"></a>    reject[i] <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(p.sim <span class="sc">&lt;</span> alpha, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb473-15"><a href="introduction-to-sample-size-determination.html#cb473-15" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb473-16"><a href="introduction-to-sample-size-determination.html#cb473-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">mean</span>(reject))</span>
<span id="cb473-17"><a href="introduction-to-sample-size-determination.html#cb473-17" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>The following R code demonstrates how to estimate and plot a power curve for this scenario. To estimate the power curve, we need to choose sample sizes at which to estimate the power of Welch’s <span class="math inline">\(t\)</span>-test to reject the null hypothesis. For this example, we will restrict the sample size to be balanced for the two groups (<span class="math inline">\(n_1 = n_2\)</span>). We choose the following 11 sample sizes at which to estimate the power of Welch’s test: 2, 5, 8, 10, 15, 20, 30, 40, 50, 60, and 75. The estimated power curve is plotted in Figure <a href="introduction-to-sample-size-determination.html#fig:sim1">7.3</a>.</p>
<div class="sourceCode" id="cb474"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb474-1"><a href="introduction-to-sample-size-determination.html#cb474-1" aria-hidden="true" tabindex="-1"></a><span class="do">## choose the number of simulation repetitions</span></span>
<span id="cb474-2"><a href="introduction-to-sample-size-determination.html#cb474-2" aria-hidden="true" tabindex="-1"></a>n_sim <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb474-3"><a href="introduction-to-sample-size-determination.html#cb474-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb474-4"><a href="introduction-to-sample-size-determination.html#cb474-4" aria-hidden="true" tabindex="-1"></a><span class="do">## set the significance level for the test</span></span>
<span id="cb474-5"><a href="introduction-to-sample-size-determination.html#cb474-5" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb474-6"><a href="introduction-to-sample-size-determination.html#cb474-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb474-7"><a href="introduction-to-sample-size-determination.html#cb474-7" aria-hidden="true" tabindex="-1"></a><span class="do">## set the sample size for each group (multiple values)</span></span>
<span id="cb474-8"><a href="introduction-to-sample-size-determination.html#cb474-8" aria-hidden="true" tabindex="-1"></a>n1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">8</span>,<span class="dv">10</span>,<span class="dv">15</span>,<span class="dv">20</span>,<span class="dv">30</span>,<span class="dv">40</span>,<span class="dv">50</span>,<span class="dv">60</span>,<span class="dv">75</span>)</span>
<span id="cb474-9"><a href="introduction-to-sample-size-determination.html#cb474-9" aria-hidden="true" tabindex="-1"></a>n2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">8</span>,<span class="dv">10</span>,<span class="dv">15</span>,<span class="dv">20</span>,<span class="dv">30</span>,<span class="dv">40</span>,<span class="dv">50</span>,<span class="dv">60</span>,<span class="dv">75</span>)</span>
<span id="cb474-10"><a href="introduction-to-sample-size-determination.html#cb474-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb474-11"><a href="introduction-to-sample-size-determination.html#cb474-11" aria-hidden="true" tabindex="-1"></a><span class="do">## set the anticipated parameters for each group</span></span>
<span id="cb474-12"><a href="introduction-to-sample-size-determination.html#cb474-12" aria-hidden="true" tabindex="-1"></a>mu1 <span class="ot">&lt;-</span> <span class="dv">0</span>; sigma1 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb474-13"><a href="introduction-to-sample-size-determination.html#cb474-13" aria-hidden="true" tabindex="-1"></a>mu2 <span class="ot">&lt;-</span> <span class="dv">1</span>; sigma2 <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb474-14"><a href="introduction-to-sample-size-determination.html#cb474-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb474-15"><a href="introduction-to-sample-size-determination.html#cb474-15" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2</span>)</span>
<span id="cb474-16"><a href="introduction-to-sample-size-determination.html#cb474-16" aria-hidden="true" tabindex="-1"></a><span class="do">## initialize vector to output results of hypothesis test for simulated data</span></span>
<span id="cb474-17"><a href="introduction-to-sample-size-determination.html#cb474-17" aria-hidden="true" tabindex="-1"></a>pwer <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb474-18"><a href="introduction-to-sample-size-determination.html#cb474-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(n1)){</span>
<span id="cb474-19"><a href="introduction-to-sample-size-determination.html#cb474-19" aria-hidden="true" tabindex="-1"></a>  <span class="do">## use helper function to estimate power</span></span>
<span id="cb474-20"><a href="introduction-to-sample-size-determination.html#cb474-20" aria-hidden="true" tabindex="-1"></a>  pwer[j] <span class="ot">&lt;-</span> <span class="fu">estPower</span>(n_sim, n1[j], n2[j], mu1, sigma1, mu2, sigma2, alpha) </span>
<span id="cb474-21"><a href="introduction-to-sample-size-determination.html#cb474-21" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb474-22"><a href="introduction-to-sample-size-determination.html#cb474-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb474-23"><a href="introduction-to-sample-size-determination.html#cb474-23" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(n1, pwer, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="st">&quot;firebrick&quot;</span>, <span class="at">ylim=</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb474-24"><a href="introduction-to-sample-size-determination.html#cb474-24" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Power curve for two-sided Welch test example&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Power&quot;</span>,</span>
<span id="cb474-25"><a href="introduction-to-sample-size-determination.html#cb474-25" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Sample size (per group)&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:sim1"></span>
<img src="topics_in_consulting_files/figure-html/sim1-1.png" alt="Visualization of power curve estimated via simulation" width="672" />
<p class="caption">
Figure 7.3: Visualization of power curve estimated via simulation
</p>
</div>
<p>We note that the R code in this subsection could be modified to facilitate simulation-based sample size determination in other scenarios. The code above runs relatively quickly but the estimated power curve is not particularly smooth. To improve this, we may want to estimate the power of Welch’s test for more sample sizes than just the 11 that were considered above. Moreover, we would likely want to use a value of <code>n_sim</code> that is at least 10000 per estimate on the power curve. This suggests that estimating power curves via simulation can be a computationally intensive process. We discuss how to speed up this process in Section <a href="introduction-to-sample-size-determination.html#samp-parallel">7.3.3</a>.</p>
</div>
<div id="samp-parallel" class="section level3 hasAnchor" number="7.3.3">
<h3><span class="header-section-number">7.3.3</span> Parallelization for Simulation-Based Sample Size Determination<a href="introduction-to-sample-size-determination.html#samp-parallel" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Parallelization can help make computing power curves or power estimates a faster process when one has access to a computer with multiple cores. Parallel computation structures the computing process such that many calculations or processes are carried out simultaneously. A large problem (computing a power curve) can often be divided into smaller ones (computing the various power estimates that comprise the power curve). These smaller problems can then be solved at the same time. The parallelization solution provided in this subsection leverages the <a href="https://cran.r-project.org/web/packages/foreach/"><strong>foreach</strong></a>, <a href="https://cran.r-project.org/web/packages/doParallel/"><strong>doParallel</strong></a>, and <a href="https://cran.r-project.org/web/packages/doSNOW/"><strong>doSNOW</strong></a> packages in R. The following R code shows how to estimate the power curve from Section <a href="introduction-to-sample-size-determination.html#samp-est-curve">7.3.2</a> using parallel computing.</p>
<div class="sourceCode" id="cb475"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb475-1"><a href="introduction-to-sample-size-determination.html#cb475-1" aria-hidden="true" tabindex="-1"></a><span class="do">## load the required packages in this order</span></span>
<span id="cb475-2"><a href="introduction-to-sample-size-determination.html#cb475-2" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(foreach)</span>
<span id="cb475-3"><a href="introduction-to-sample-size-determination.html#cb475-3" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(doParallel)</span>
<span id="cb475-4"><a href="introduction-to-sample-size-determination.html#cb475-4" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(doSNOW)</span>
<span id="cb475-5"><a href="introduction-to-sample-size-determination.html#cb475-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb475-6"><a href="introduction-to-sample-size-determination.html#cb475-6" aria-hidden="true" tabindex="-1"></a><span class="do">## set up the multiple cores for parallelization</span></span>
<span id="cb475-7"><a href="introduction-to-sample-size-determination.html#cb475-7" aria-hidden="true" tabindex="-1"></a><span class="do">## cores[1] returns the number of cores on your machine;</span></span>
<span id="cb475-8"><a href="introduction-to-sample-size-determination.html#cb475-8" aria-hidden="true" tabindex="-1"></a><span class="do">## this command makes a parallel computing environment with cores[1]-1 cores;</span></span>
<span id="cb475-9"><a href="introduction-to-sample-size-determination.html#cb475-9" aria-hidden="true" tabindex="-1"></a><span class="do">## this frees up a core to do other processes (do not assign more than cores[1]-1 cores).</span></span>
<span id="cb475-10"><a href="introduction-to-sample-size-determination.html#cb475-10" aria-hidden="true" tabindex="-1"></a>cores<span class="ot">=</span><span class="fu">detectCores</span>()</span>
<span id="cb475-11"><a href="introduction-to-sample-size-determination.html#cb475-11" aria-hidden="true" tabindex="-1"></a>cl <span class="ot">&lt;-</span> <span class="fu">makeSOCKcluster</span>(cores[<span class="dv">1</span>]<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb475-12"><a href="introduction-to-sample-size-determination.html#cb475-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb475-13"><a href="introduction-to-sample-size-determination.html#cb475-13" aria-hidden="true" tabindex="-1"></a><span class="do">## determine the number of parallel processes (the number of points on the power curve)</span></span>
<span id="cb475-14"><a href="introduction-to-sample-size-determination.html#cb475-14" aria-hidden="true" tabindex="-1"></a>n_loop <span class="ot">&lt;-</span> <span class="fu">length</span>(n1)</span>
<span id="cb475-15"><a href="introduction-to-sample-size-determination.html#cb475-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb475-16"><a href="introduction-to-sample-size-determination.html#cb475-16" aria-hidden="true" tabindex="-1"></a><span class="do">## choose the number of simulation repetitions</span></span>
<span id="cb475-17"><a href="introduction-to-sample-size-determination.html#cb475-17" aria-hidden="true" tabindex="-1"></a>n_sim <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb475-18"><a href="introduction-to-sample-size-determination.html#cb475-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb475-19"><a href="introduction-to-sample-size-determination.html#cb475-19" aria-hidden="true" tabindex="-1"></a><span class="do">## set the significance level for the test</span></span>
<span id="cb475-20"><a href="introduction-to-sample-size-determination.html#cb475-20" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb475-21"><a href="introduction-to-sample-size-determination.html#cb475-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb475-22"><a href="introduction-to-sample-size-determination.html#cb475-22" aria-hidden="true" tabindex="-1"></a><span class="do">## set the sample size for each group (multiple values)</span></span>
<span id="cb475-23"><a href="introduction-to-sample-size-determination.html#cb475-23" aria-hidden="true" tabindex="-1"></a>n1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">8</span>,<span class="dv">10</span>,<span class="dv">15</span>,<span class="dv">20</span>,<span class="dv">30</span>,<span class="dv">40</span>,<span class="dv">50</span>,<span class="dv">60</span>,<span class="dv">75</span>)</span>
<span id="cb475-24"><a href="introduction-to-sample-size-determination.html#cb475-24" aria-hidden="true" tabindex="-1"></a>n2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">8</span>,<span class="dv">10</span>,<span class="dv">15</span>,<span class="dv">20</span>,<span class="dv">30</span>,<span class="dv">40</span>,<span class="dv">50</span>,<span class="dv">60</span>,<span class="dv">75</span>)</span>
<span id="cb475-25"><a href="introduction-to-sample-size-determination.html#cb475-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb475-26"><a href="introduction-to-sample-size-determination.html#cb475-26" aria-hidden="true" tabindex="-1"></a><span class="do">## set the anticipated parameters for each group</span></span>
<span id="cb475-27"><a href="introduction-to-sample-size-determination.html#cb475-27" aria-hidden="true" tabindex="-1"></a>mu1 <span class="ot">&lt;-</span> <span class="dv">0</span>; sigma1 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb475-28"><a href="introduction-to-sample-size-determination.html#cb475-28" aria-hidden="true" tabindex="-1"></a>mu2 <span class="ot">&lt;-</span> <span class="dv">1</span>; sigma2 <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb475-29"><a href="introduction-to-sample-size-determination.html#cb475-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb475-30"><a href="introduction-to-sample-size-determination.html#cb475-30" aria-hidden="true" tabindex="-1"></a><span class="do">## this code sets up a progress bar; this is helpful if you have less than n_loop</span></span>
<span id="cb475-31"><a href="introduction-to-sample-size-determination.html#cb475-31" aria-hidden="true" tabindex="-1"></a><span class="do">## cores available (you can see the proportion of the smaller tasks that have been completed)</span></span>
<span id="cb475-32"><a href="introduction-to-sample-size-determination.html#cb475-32" aria-hidden="true" tabindex="-1"></a><span class="fu">registerDoSNOW</span>(cl)</span>
<span id="cb475-33"><a href="introduction-to-sample-size-determination.html#cb475-33" aria-hidden="true" tabindex="-1"></a>pb <span class="ot">&lt;-</span> <span class="fu">txtProgressBar</span>(<span class="at">max =</span> n_loop, <span class="at">style =</span> <span class="dv">3</span>)</span>
<span id="cb475-34"><a href="introduction-to-sample-size-determination.html#cb475-34" aria-hidden="true" tabindex="-1"></a>progress <span class="ot">&lt;-</span> <span class="cf">function</span>(n) <span class="fu">setTxtProgressBar</span>(pb, n)</span>
<span id="cb475-35"><a href="introduction-to-sample-size-determination.html#cb475-35" aria-hidden="true" tabindex="-1"></a>opts <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">progress =</span> progress)</span>
<span id="cb475-36"><a href="introduction-to-sample-size-determination.html#cb475-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb475-37"><a href="introduction-to-sample-size-determination.html#cb475-37" aria-hidden="true" tabindex="-1"></a><span class="do">## the foreach() function facilitates parallelization (described below)</span></span>
<span id="cb475-38"><a href="introduction-to-sample-size-determination.html#cb475-38" aria-hidden="true" tabindex="-1"></a>pwer2 <span class="ot">&lt;-</span> <span class="fu">foreach</span>(<span class="at">j=</span><span class="dv">1</span><span class="sc">:</span>n_loop, <span class="at">.combine=</span><span class="st">&quot;c&quot;</span>, <span class="at">.packages =</span> <span class="fu">c</span>(<span class="st">&quot;foreach&quot;</span>),</span>
<span id="cb475-39"><a href="introduction-to-sample-size-determination.html#cb475-39" aria-hidden="true" tabindex="-1"></a>                               <span class="at">.options.snow=</span>opts) <span class="sc">%dopar%</span> {</span>
<span id="cb475-40"><a href="introduction-to-sample-size-determination.html#cb475-40" aria-hidden="true" tabindex="-1"></a>                                 <span class="fu">set.seed</span>(j)</span>
<span id="cb475-41"><a href="introduction-to-sample-size-determination.html#cb475-41" aria-hidden="true" tabindex="-1"></a>                                 </span>
<span id="cb475-42"><a href="introduction-to-sample-size-determination.html#cb475-42" aria-hidden="true" tabindex="-1"></a>                                 <span class="do">## function outputs the estimated power for each</span></span>
<span id="cb475-43"><a href="introduction-to-sample-size-determination.html#cb475-43" aria-hidden="true" tabindex="-1"></a>                                 <span class="do">## point on the curve (from previous code block)</span></span>
<span id="cb475-44"><a href="introduction-to-sample-size-determination.html#cb475-44" aria-hidden="true" tabindex="-1"></a>                                 <span class="fu">estPower</span>(n_sim, n1[j], n2[j], mu1, sigma1, mu2, sigma2, alpha)</span>
<span id="cb475-45"><a href="introduction-to-sample-size-determination.html#cb475-45" aria-hidden="true" tabindex="-1"></a>                               }</span></code></pre></div>
<p>The previous code block can be used to reproduce the estimated power curve from earlier (just replace <code>pwer</code> with <code>pwer2</code> in the plot command). The <code>foreach()</code> function faciliates the parallelization for this example. We discuss several of its important arguments below:</p>
<ul>
<li><code>j</code>: this input should take the form <code>1:n_loop</code>, where <code>n_loop</code> is the number of tasks that must be computed in parallel.</li>
<li><code>.combine</code>: this argument denotes how the objects returned by each parallel task should be combined. Specifying <code>"c"</code> will concatentate these results into a vector, and using <code>cbind</code> or <code>rbind</code> can be used to combine vectors into a matrix. For this example, each parallel task returns a single power estimate, so we selected <code>"c"</code>.</li>
<li><code>.packages</code>: this argument should be a character vector denoting the packages that the parallel tasks depend on. For this situation, we do not need the <strong>foreach</strong> package to compute the power estimates, but this shows the format that this argument must take if we do have any dependencies for the parallel tasks.</li>
<li><code>options.snow</code>: this argument sets up the progress bar. As long as <code>n_loop</code> is modified as necessary, we do not need to change any other code associated with the progress bar to modify this code for a different example.</li>
<li><code>.errorhandling</code>: this argument is set to <code>stop</code> by default. This means that if one of the cores encounters an error message when computing a smaller task, the execution of all tasks is stopped. We recommend using this default setting so that you are alerted to the issue and can investigate potential problems with the code.</li>
</ul>
<p>If you have a very computationally intensive sample size calculation, you can run your code on the <a href="https://uwaterloo.ca/math-faculty-computing-facility/services/research-and-staff-windows-servers">MFCF servers</a> for graduate students, faculty, and staff in the Math Faculty. You should have up to 72 cores available when using the MFCF servers, which is likely more computing power than is available on a desktop computer.</p>
<p>Finally, the above code block computed the power estimate for each point on the power curve using a regular for loop. Each of the estimates on the power curve were computed in parallel. If it takes a very long time to compute a single power estimate, then you may want to compute each power estimate in parallel and iterate through all power estimates on the curve using a regular for loop. This could be done by modifying the code block above. We could replace <code>estPower()</code> with a function that returns a binary result to denote whether the null hypothesis was rejected for a single simulation run. We would want to then specify <code>j=1:n_sim</code> for the <code>foreach()</code> function call, and then we would wrap this <code>foreach()</code> function call in a regular for loop from <code>i = 1:n_loop</code>. We note that it is certainly not necessary to parallelize a sample size calculation, but it can be helpful if the calculation is very computationally intensive.</p>
</div>
</div>
<div id="samp-beyond" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Beyond Sample Size Determination<a href="introduction-to-sample-size-determination.html#samp-beyond" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Sound experimental design does not end with sample size determination. It can be helpful to discuss concepts that are related to sample size determination with the client. For instance, maybe the client has decided that they would like to collect 50 observations per group for the two groups in their study. In this situation, it would be a good idea to discuss <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3136079/">randomization</a> with the client. It is not ideal to simply assign the first 50 observations to the first treatment and the last 50 observations to the second treatment.</p>
<p>There may also be situations where a client might want to collect a smaller sample than recommended and then decide whether or not to collect a larger sample based on the results from analyzing the smaller sample. This is related to the statistical concept of <a href="https://gopractice.io/data/peeking-problem/">peeking</a>, where we monitor the data as they are observed and decide whether to continue or stop the experiment. It is not ideal to observe the data in stages, but it should be disclosed as part of the analysis that the data were not observed all at once if the data from both samples is used as part of the study.</p>

</div>
</div>



<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-cohen" class="csl-entry">
Cohen, Jacob. 2013. <em>Statistical Power Analysis for the Behavioral Sciences</em>. Routledge.
</div>
<div id="ref-walker.nowacki" class="csl-entry">
Walker, Esteban, and Amy S Nowacki. 2011. <span>“Understanding Equivalence and Noninferiority Testing.”</span> <em>Journal of General Internal Medicine</em> 26 (2): 192–96.
</div>
<div id="ref-wasserstein.lazar" class="csl-entry">
Wasserstein, Ronald L, and Nicole A Lazar. 2016. <span>“The ASA Statement on p-Values: Context, Process, and Purpose.”</span> Taylor &amp; Francis.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introduction-to-questionnaire-design.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="general-guidelines.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
